### ISSUE TITLE
Fix arrow Card Unbonding

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#101]
Fix the arrow on the light mode in the pool PDP on the unbending card.

Implementation:
![issue-on-buttons](https://user-images.githubusercontent.com/13519292/161581762-daa9a7ee-abae-452e-9dd6-a099ad7decbd.jpg)

**Comment by EnricoBarbieri1997** [comment]
Previously fixed in 77a8d48f42c204c1aabc31675f283a2d13da2fe9
