### ISSUE TITLE
Use "My" instead of "Your"

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#104]
Give a look at all the texts and substitute **Your** into **My**. 
E.g., **Your pools** into **My pools**.

**Comment by EnricoBarbieri1997** [comment]
Reviewed with copy and decided that "Your pools" is the only place where it makes changing to "My"

**Comment by Giorgionocera** [comment]
@giannnni you and Giulio need to talk about texts on the website.

**Comment by giannnni** [comment]
Fixed as suggested 
![image](https://user-images.githubusercontent.com/92384659/162424337-3a677180-39f2-4649-8c78-17420fa88c38.png)

**Comment by Giorgionocera** [comment]
Maybe I was not so clear. We need to check all the website texts. Design and Marketing teams should work together to analyze the texts (this is to avoid too long texts, for example).

**Comment by giannnni** [comment]
Done as requested. 👌

**Comment by Giorgionocera** [comment]
Thank you all!
