### ISSUE TITLE
Change progress bar behavior

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#108]
The progress bar behavior needs to change. We need to invert the bar in order to obtain the effect of "remaining" and not "used". So mathematically "1-x" instead of "x" should start from the right.
In this way, we'll have the "full gradient" on right and the "empty" piece of the bar on the right.

Implementation:
![telegram-cloud-photo-size-4-5938230021653116332-w](https://user-images.githubusercontent.com/13519292/161731770-f764f9c6-7e20-4967-9c6e-709c9a2d0fd2.jpg)

**Comment by giannnni** [comment]
Fixed the progress bar behaviour. Now the UI component shows a bar starts all filled with gradient that decrease with right align. 
Moreover, we also decided to remove progress bars below (linked to single incentive) for readability need.

 <img width="637" alt="Schermata 2022-04-07 alle 13 10 21" src="https://user-images.githubusercontent.com/92384659/162186088-7effc9f7-7ea5-48ba-aeb7-61b65cf43b40.png">

**Comment by DavideSegullo** [comment]
@EnricoBarbieri1997 You can sync with dev branch, i changed the layout of each card, but you should change padding like on figma

**Comment by Giorgionocera** [comment]
Thank you all!

**Comment by Giorgionocera** [comment]
Angelo asked to restore the previous implementation. Please, @DavideSegullo let's move in development.

**Comment by Giorgionocera** [comment]
Thank you all again!
