### ISSUE TITLE
Add faucet on Sinfonia

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#112]
We need to add the faucet button on Sinfonia.
If something is not clear enough, you can ask the design team.

We need something like this:
![get-btsg](https://user-images.githubusercontent.com/13519292/161758042-56c1a354-c372-4751-9a57-a127ff402583.jpg)

**Comment by giannnni** [comment]
The solution implemented. 
![image](https://user-images.githubusercontent.com/92384659/161771092-ed312630-0d13-4358-b874-3919cd35ca2a.png)

**Comment by Giorgionocera** [comment]
Thank you!
