### ISSUE TITLE
Change Menu on Mobile 

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#113]
Remove the Bottom Nav Bar from Mobile version (responsive). Instead of that include all the main pages inside the hamburger menu.

**Comment by EnricoBarbieri1997** [comment]
![image](https://user-images.githubusercontent.com/12893767/162188338-e0a2db0e-eae5-49b7-bebe-b9e49f43fcdb.png)
We need a design for the inner menu

**Comment by giannnni** [comment]
Fixed Menu. 

![image](https://user-images.githubusercontent.com/92384659/162195784-f534f3bd-7ade-4ab9-8797-8007638db697.png)

**Comment by Giorgionocera** [comment]
@EnricoBarbieri1997 I think the menu needs an update.

Implementation:
![sinfonia pages dev_(iPhone 12 Pro) (1)](https://user-images.githubusercontent.com/13519292/162686631-a64b1dec-3c76-4193-a746-5e764e71f46c.png)

Design:
![image](https://user-images.githubusercontent.com/13519292/162686673-03215c5e-f544-4722-b71e-21e84935a09b.png)

You can also ask @giannnni to be sure.

**Comment by EnricoBarbieri1997** [comment]
Fixed in a branch merged recently.

**Comment by Giorgionocera** [comment]
Thank you!
