### ISSUE TITLE
Change image on Adam Clay

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#125]
On Adam Clay Fan token page we need to change the image on top in order to show a larger part of the image. We can try to resize the image (make it smaller in width) and then create a fake background on the left and right. In this way, we'll get a more complete image.

Implementation:
![change-image](https://user-images.githubusercontent.com/13519292/162045296-6050d590-ae40-49b2-9c73-1743be5fe6cf.jpg)

**Comment by giannnni** [comment]
Fixed as suggested. ![image](https://user-images.githubusercontent.com/92384659/162172305-9625b547-e3dc-4fcf-b4a3-b3100b5888a9.png)

**Comment by Giorgionocera** [comment]
Thank you @giannnni. @DavideSegullo we can move forward with the implementation.

**Comment by Giorgionocera** [comment]
Thank you!
