### ISSUE TITLE
Define Tooltip message - Single Asset

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#134]
We need a small text inside this tooltip to explain how "add liquidity" works when the user want to put in only one asset instead of a pair.
The tooltip appears on hover on icon and label "Single Asset LP"

Character limit: 100

<img width="756" alt="Schermata 2022-04-12 alle 12 45 53" src="https://user-images.githubusercontent.com/92384659/162944567-1f4ff4b0-d9dc-44fb-aee0-d9932914bd90.png">

**Comment by giulioaiello** [comment]
Copy: Provide liquidity without swapping the % of the tokens to match the criteria. You are participating with both assets.

**Comment by Giorgionocera** [comment]
Thank you all!
