### ISSUE TITLE
Define Tooltip message - Unbonding

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#135]
We need a small text to explain in a tooltip what "unbonding period" is and what's the difference between the options below.
The tooltip appears on the hover icon and the label "Select Unbonding Period".

Character limit: 100

<img width="555" alt="Schermata 2022-04-12 alle 13 16 18" src="https://user-images.githubusercontent.com/92384659/162948757-9fa99f2f-e7e3-4b32-a59e-66eee050ef19.png">

**Comment by giulioaiello** [comment]
Copy: It indicates a countdown, after the unbonding period you will be able to remove liquidity from the pool.
Remember: The longer you leave bonded tokens in the pool, the more rewards you will receive.

**Comment by Giorgionocera** [comment]
Thank you all!
