### ISSUE TITLE
Define Text for Privacy Checkbox - PDP

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#136]
We need a real text for this checkbox below the newsletter. 
Find further information asking @Giorgionocera if this component is related only to the artist news. If not, maybe we could leave the copy as it is.

<img width="922" alt="Schermata 2022-04-12 alle 13 23 19" src="https://user-images.githubusercontent.com/92384659/162950340-bdeb4dac-9ac0-412e-b215-dae5b049b6e2.png">
.

**Comment by Giorgionocera** [comment]
@giulioaiello , we need to consider that the field is linked to a mailchimp-list-id. For this reason, the copy depends on what the mailchimp-list-id is related to.
