### ISSUE TITLE
Define Tooltip message - Slippage

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#137]
We need a small text to explain what is slippage, letting user understand what "Slippage Tolerance" means inside a swap operation.
The tooltip appears on hover on icon and label "Slippage Tolerance"

Character Limit: 100

<img width="674" alt="Schermata 2022-04-12 alle 13 32 05" src="https://user-images.githubusercontent.com/92384659/162951346-de86d616-89d2-400f-a778-bc09901e154a.png">

**Comment by giulioaiello** [comment]
Copy: Slippage is the difference between a trade’s expected and actual price.

**Comment by Giorgionocera** [comment]
Thank you all!
