### ISSUE TITLE
Check "Cookie Bar" copy

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#138]
Just for double check.

<img width="1180" alt="Schermata 2022-04-12 alle 13 36 12" src="https://user-images.githubusercontent.com/92384659/162951591-5e21bfc2-f2d2-4bfb-baa8-4a2bd4e8ac90.png">

**Comment by Giorgionocera** [comment]
@giulioaiello the text is the same we used on the https://bitsong.io website. If you agree, we can move forward with development.

**Comment by Giorgionocera** [comment]
Related with #93 .
