### ISSUE TITLE
Define abstract - Liquidity Mining 

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#139]
We need a small text below the title just to introduce "Liquidity Mining" and "Earning" topics.

Character Limit: 100

<img width="667" alt="Schermata 2022-04-12 alle 13 38 39" src="https://user-images.githubusercontent.com/92384659/162952396-15b0dcb1-672e-414e-bb17-af2c1d49bbee.png">
.

**Comment by DavideSegullo** [comment]
@giulioaiello What is the text?

**Comment by giulioaiello** [comment]
short versione: Liquidity mining is a process in which crypto holders lend assets to a decentralized exchange in return for rewards.

long version (preferred): Liquidity mining is a decentralized finance mechanism wherein participants provide some of their crypto assets into various liquidity pools, from which they're rewarded with tokens and fees.

**Comment by Giorgionocera** [comment]
Thank you all!
