### ISSUE TITLE
Define Tooltip message - Epoch

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#140]
We need a small text to explain what is an epoch and what timeframe corresponds in Sinfonia Platform.
The tooltip appears on hover on icon and label "X Epoch left"

Character Limit: 100

<img width="626" alt="Schermata 2022-04-12 alle 14 18 05" src="https://user-images.githubusercontent.com/92384659/162961257-9e0f8b7d-e5db-4c64-b38c-abf46b2e23d8.png">

**Comment by giulioaiello** [comment]
Copy: An epoch is considered a specific period of time. On Sinfonia an epoch corresponds to 24 hours.

**Comment by Giorgionocera** [comment]
We also need to make it dynamic.
