### ISSUE TITLE
Define Tooltip message - LP Tokens

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#141]
We need a small text to explain what is a LP Token and what means the "amount" showed in the UI.
The tooltip appears on hover on icon and label "Available LP Tokens"

Character Limit: 100

<img width="387" alt="Schermata 2022-04-12 alle 14 22 35" src="https://user-images.githubusercontent.com/92384659/162961973-8cb65de8-489a-4fdb-81b0-697fb9aba35b.png">

**Comment by Giorgionocera** [comment]
Thank you all!
