### ISSUE TITLE
Change Label "My Bondings"

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#142]
We need to change the label "my bondings" into "my bonded assets" inside the Pool's Details Page.

<img width="350" alt="Schermata 2022-04-12 alle 14 27 18" src="https://user-images.githubusercontent.com/92384659/162962452-13acbaa5-b89c-440e-9bbe-57ca9a65e41b.png">

**Comment by Giorgionocera** [comment]
Thank you all!
