### ISSUE TITLE
Define subtitle - Incentives

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#143]
We need a small text inside the card (just below the Pool incentive) to show more infos about the relative unbonding period and the duration of the incentives expressed in epoch times (we could repeat infos, just to be sure)

Character Limit: 80

<img width="545" alt="Schermata 2022-04-12 alle 14 44 54" src="https://user-images.githubusercontent.com/92384659/162965219-e699bc33-9d7d-4280-be35-2d395bdf5a9c.png">

**Comment by DavideSegullo** [comment]
@giulioaiello What is the text?

**Comment by giulioaiello** [comment]
Copy: Bond Assets to earn liquidity rewards and swap fees.

**Comment by Giorgionocera** [comment]
Thank you all!
