### ISSUE TITLE
Add hint on swap with 0 balance

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#150]
When a new user comes to Sinfonia, even if he has got a balance that is greater than 0, until he does not transfer his coins on Osmosis, his balance on the swap page will be zero.
This is normal behavior to those who know how Sinfonia works but not for the Newby. For this reason, I propose to you all, to add a hint (informative I with a tooltip) explaining with a **short** text, why this is happening.
This tooltip will be shown only when you have 0 balance on Osmosis but you have a balance greater than 0 on BitSong.
What do you think about it?

@giannnni @giulioaiello @DavideSegullo.

**Comment by Giorgionocera** [comment]
Thank you @giulioaiello. What about @giannnni and @DavideSegullo?

**Comment by DavideSegullo** [comment]
It's okay for me, that can be helpful

**Comment by Giorgionocera** [comment]
@giannnni, can you say me what you think about this?

**Comment by giannnni** [comment]
@Giorgionocera agree with this solution.

**Comment by Giorgionocera** [comment]
Nice! Thank you. @DavideSegullo we can move to development!

**Comment by DavideSegullo** [comment]
@giannnni Do we have a design for that?

**Comment by Giorgionocera** [comment]
Thank you all!
