### ISSUE TITLE
Ledger Support

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/sinfonia-ui#152]
As reported on discord, the ledgers don't work.

Error:

> Type URL '/osmosis.gamm.v1beta1.MsgSwapExactAmountIn' does not exist in the Amino message type register. If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. If you think this message type should be included by default, please open an issue at https://github.com/cosmos/cosmjs/issues.

**Comment by Giorgionocera** [comment]
Thank you!
