### ISSUE TITLE
Playground Description 

### ISSUE THREAD

**Issue by giulioaiello** [bitsongofficial/sinfonia-ui#153]
**Playgroung**

Welcome to Sinfonia incentivized Testnet!
Each participant might be able to get great rewards in BTSG and FanTokens for simply playing with the platform.

CTA: Read the official announcement 

**Prizes:**

- $25000 in BTSG;
- 1% of the Loyalty Program of the first 10 FanTokens listed on Sinfonia Testnet.

CTA: Post on twitter

**Comment by giannnni** [comment]
Resolved as following
![image](https://user-images.githubusercontent.com/92384659/165525916-e7176ffa-148f-4536-8ca2-f68641236730.png)

**Comment by DavideSegullo** [comment]
@giulioaiello we need the twitter link and medium for the official announcement

**Comment by Giorgionocera** [comment]
Thank you all!
