### ISSUE TITLE
Hide 0 bonding

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#158]
Angelo advised us: "If there is no incentive for some bonding lock period, we have to hide the boxes for those locks".
In this sense, @giannnni , I ask you what you think if we directly hide the boxes.
In this case, if for example, no incentives are present for the first 2 lock periods, the 3rd lock period will be the only one present.
What do you propose to do in such a scenario? to put it in the center? or to put it on the left?
Do you have any other advice?

![hide-bonding-0](https://user-images.githubusercontent.com/13519292/166229447-61174940-b72a-4d0a-ad7c-c3567b3a1443.jpg)

**Comment by angelorc** [comment]
I prefer to start from the left

**Comment by giannnni** [comment]
I guess is better to preserve the UI just hiding the buttons referred to empty incentive periods. 

![image](https://user-images.githubusercontent.com/92384659/167110891-b764c231-3db8-4ecf-9110-8f49d939ba64.png)

**Comment by Giorgionocera** [comment]
Thank you!
