### ISSUE TITLE
Default table sorting in assets page

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#161]
The table on the assets page needs to be sorted by available coins as default ordering. Moreover, the ids (number at the beginning of each row) should be added as an "ID" and needs to change in the different sorting.

Implementation:
![order-available](https://user-images.githubusercontent.com/13519292/166266414-2c498417-1e09-4769-bf06-fa3ffdf299bf.jpg)

**Comment by DavideSegullo** [comment]
@Giorgionocera I think we can remove the ID's column here, because we don't have a ranking system for the assets

**Comment by Giorgionocera** [comment]
I saw there is a different implementation, it is ordered by Qty. In my opinion (even if it was requested to be sorted by "available"), it is better as it is now. So I can consider this issue closed. Thank you!
