### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#176]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I have balance BTSG but unable to swap 
![image](https://user-images.githubusercontent.com/22148449/167450702-d05df62b-9c50-49e4-96dc-8c576618cedf.png)

### Describe the issue behavior

zero balance unable to swap

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

 99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
As it is possible to see from your screenshot, the amount of BTSG you have is stored on the BitSong testnet chain. As you can read from the message displayed in your screenshot, you need to transfer those BTSG to the Osmosis testnet to trade them. You can do it directly from the assets page.

This information is also available through the guide.
It is definitively not a bug.
