### ISSUE TITLE
[Competition Bug]: Unable to transfer the balance of the required amount

### ISSUE THREAD

**Issue by Fr1SeZ** [bitsongofficial/sinfonia-ui#177]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

When entering an amount less than 1000, there was such a problem as in the screenshot 
![Снимок экрана 2022-05-09 210250](https://user-images.githubusercontent.com/93135119/167450889-afd76d23-a651-4328-b22e-5122336fa03a.jpg)

### Describe the issue behavior

Unable to transfer from btsg to osmois

### BitSong Public Address

bitsong1928nvwxp7fsfcurg65n7dsz06v994txla4qr9m

### Osmosis Public Address

osmo1aaa33ecm76hua0y5djtnlwrx5hgxpx37xalje5

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
As it is possible to see from the screenshot, the form shows you that you are doing a dangerous operation: "You are moving a big amount of BTSG from BitSong chain to Osmosis Chain". It is not an error, and you can see more information by hovering over the information icon. Give it a try.

It is definitively not a bug.
