### ISSUE TITLE
[Competition Bug]: Swap Tokens and incorrect spelling

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#181]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Amount must be a greater then zero "wrong spelling" Correct Spelling **_Amount must be a greater than zero_**
Unable to swap and 0.000001 is greater than 0 

My Solution is "Set the minimum required amount in swap tokens"

![image](https://user-images.githubusercontent.com/22148449/167453938-59451efa-d15e-43b5-9022-e669864eb0e4.png)

### Describe the issue behavior

Swap Tokens and incorrect spelling 

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
I'll answer you by points:

1. Textual issue
> Amount must be a greater then zero "wrong spelling" Correct Spelling Amount must be a greater than zero

**Thank you** for this suggestion in the message. I do not consider it a "bug". It is a suggestion for a message. No unwanted behavior is generated.


2. Too low value
> Unable to swap and 0.000001 is greater than 0

Even in this case, I do not consider the behavior a "bug". You cannot swap your tokens if the obtained value is lower than a threshold (and in this sense, it is **represented** as 0). It is a feature related to the chosen display type.
