### ISSUE TITLE
[Competition Bug]: CANNOT SWAP BITSONG TO BLACKJACKRECORDS

### ISSUE THREAD

**Issue by cbsantos90** [bitsongofficial/sinfonia-ui#189]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

1. open the BitSong/BlackjackRecords pair on swap section by this link https://testnet.sinfonia.zone/swap?from=BTSG&to=BJKS
2. the default slippage tolerance is 1%
3. try to swap 10 BitSongs to BlackjackRecords
![bug 3](https://user-images.githubusercontent.com/98073517/167458499-466bf286-9be4-4807-8ead-5538650dde25.gif)

*try using light mode

### Describe the issue behavior

bug : unable to swap transactions on BitSong/BlackjackRecords token pairs
details : the transaction always fails every time you want to do a swap transaction on this pair (BitsSong/BlackjackRecords). I did the swap with light mode, thou i don't know if it affected or not but i just want to tell the the web's appearance condition on my device. 
Error when broadcasting tx 5E20D0873C7CCEA79C24EBCB58A2EF78805C6AEFD50A4B7D04722511848D9317 at height 1002. Code: 7; Raw log: failed to execute message; message index: 0: ibc/0A4701632EED3332CD812498463F09B2247F04AD9BC390D9A0F84F8452F501C4 token is lesser than min amount: calculated amount is lesser than min amount

![bug 3](https://user-images.githubusercontent.com/98073517/167459304-6b1e6f3b-acf4-4fb0-af77-05198869f8e0.gif)

### BitSong Public Address

bitsong1g0l3hla7jaf8z9agskdejp3kzh60ufxm6852pj

### Osmosis Public Address

osmo1wtcrmmyysjxln7gkgftncy44m0dl4sr009y5tl

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #185

**Comment by cbsantos90** [comment]
no sir. honestly it only happened on BitSong/BlackjackRecords pair
