### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Galihsaptahadi** [bitsongofficial/sinfonia-ui#190]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [ ] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

the step that must be reproduced is to increase the speed of the execution network so that it can execute faster than seconds because the more the network is used, the more it affects the performance itself.

### Describe the issue behavior

I saw something went wrong when swap BTSG to blackjack record failed 2x
the first one with 1% slippage failed and the second one with 3% slippage was successful but there was something strange about that failure that my BTSG coins were reduced by 2x even though only 1 succeeded
the initial balance is around 7500 and after the flop the remainder is 1933.
also when going to add BJKS/BTSG stakes, the transaction failed 1x until the second time it was successful.

![Screenshot (149)](https://user-images.githubusercontent.com/95604585/167459384-b7876eb3-e433-4e84-8d8a-b88368209e54.png)
![Screenshot (150)](https://user-images.githubusercontent.com/95604585/167459397-c89ec6b0-4d42-4d27-8db3-adcd60898243.png)
![Screenshot (148)](https://user-images.githubusercontent.com/95604585/167459439-38d6d947-2088-442d-8c5c-d8ef5301c63c.png)

### BitSong Public Address

bitsong17e8sna620szvpkdvft7qus2ulet7a3vxacy3ht

### Osmosis Public Address

osmo1a4hany72n8cny5d334gw2smp86v0efz5tm3c8r

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This is simply a testnet network. It is not a mainnet and for this reason, no high performance is allocated. This information (this is a testnet) was provided through different channels.

Thank you for your advice. I don't think this is an issue.

**Comment by Galihsaptahadi** [comment]
Then why did my coins decrease even though the transaction failed?

**Comment by Giorgionocera** [comment]
Are you able to demonstrate that the transaction fails but your coins are decreasing?
It feels very strange to me.
