### ISSUE TITLE
[Competition Bug]: Add Liquidity and incorrect spelling

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#191]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Amount must be a greater then zero "wrong spelling" Correct Spelling **Amount must be a greater than zero**
Unable to add liquidity and 0.000000011 is greater than 0

My Solution is "Set the minimum required amount in add liquidity "

### Describe the issue behavior

Add Liquidity and incorrect spelling

![image](https://user-images.githubusercontent.com/22148449/167460108-be950f64-4298-4e9f-9095-a9b7a6abdb74.png)

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #181
