### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by anhsojack** [bitsongofficial/sinfonia-ui#193]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Balance wallet is showing wrong balance
![Uploading bitsong_wrongbalance.png…]()

### Describe the issue behavior

It's happened after i've transferred BTSG token from bitsong testnet to osmosis testnet. In my case, before i did i have around 8000 BTSG. I've decided to transfer 1000 BTSG. After everything has done the UI is showing  the remain balance that has increased to 9000 BTSG

### BitSong Public Address

bitsong17l4z6379ngl72vuqtdh8cskwgu87lj2r8cs6sw

### Osmosis Public Address

osmo19drv8pq2sap7nkx8yawzxugwx3e3ndwudzhjwh

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
You started with 10k tBTSG. Your image is not available.

Cannot evaluate.
