### ISSUE TITLE
[Competition Bug]: Assets Sort Tokens (Symbol Price Chain)

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#195]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Unable to sort by Symbol & Price & Chain

![image](https://user-images.githubusercontent.com/22148449/167463182-71efebbc-4b02-4b35-8aa3-b369e7f71d63.png)

### Describe the issue behavior

Assets Sort Tokens (Symbol Price Chain)

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This is a choice, it is not a bug.
