### ISSUE TITLE
[Competition Bug]: Bug in Hyperlink

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#196]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Hyperlinks go to the wrong destination 

I try D9 Recordings and I click swap tokens but a wrong destination

![image](https://user-images.githubusercontent.com/22148449/167464650-a1c34eb8-869d-4a32-9a56-0c0e7a422092.png)

### Describe the issue behavior

Bug in Hyperlink 

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #178 (2h before).
