### ISSUE TITLE
Transaksi Failed

### ISSUE THREAD

**Issue by samsolpratama** [bitsongofficial/sinfonia-ui#197]
transaction failed, I can't swap BTSG tokens, 2 tokens are complete, other tokens can't be swapped.
then when ad lp the transaction failed 2 times.
my addres bitsong1w4dfqfl44x0ces3gv2lnxzl7h68f9hwkauzwjf
![Screenshot_135](https://user-images.githubusercontent.com/79659840/167466232-95fd73d5-1ae0-486d-9f02-1b20a8139cfb.png)
![Screenshot_136](https://user-images.githubusercontent.com/79659840/167466243-e233ffed-e987-4579-af17-48b5096630ec.png)
![Screenshot_137](https://user-images.githubusercontent.com/79659840/167466246-11b27ca6-0e0d-494c-9671-d8ceb7cfa89b.png)

**Comment by Giorgionocera** [comment]
Failing transactions were due to high traffic. This is not definitely a bug.
