### ISSUE TITLE
[Competition Bug]: Do not have transaction history

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#198]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

When I look or click on my wallet or account, no transaction shows up
![image](https://user-images.githubusercontent.com/22148449/167467851-1a06686f-0b86-4732-b353-314a8d7d08fa.png)

### Describe the issue behavior

Do not have Transaction History and also Search Features 
Example1: I want to see my newest to oldest transaction
Example2: I want to see my all transaction in BTSG

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
In this testnet network, no explorer was provided. This is not a bug. It is only a choice for the testnet.
