### ISSUE TITLE
[Competition Bug]: Buttons Not Visible

### ISSUE THREAD

**Issue by jcbm123143** [bitsongofficial/sinfonia-ui#200]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I have a problem regarding searching the buttons are not visible and need to drag down to see the buttons
![image](https://user-images.githubusercontent.com/22148449/167470998-3dd3937e-abb1-4723-ab68-758f6716d03f.png)

### Describe the issue behavior

Not Visible and need to freeze all buttons 

### BitSong Public Address

bitsong1kac8reet5660tkw5ryx45asf6f26ujufypls3q

### Osmosis Public Address

osmo1kac8reet5660tkw5ryx45asf6f26ujufqn7g9a

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.51

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
It is a UI choice. It is definitely not a bug.
