### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by keenOnFrontEnd** [bitsongofficial/sinfonia-ui#203]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

1) buy CLAY tokens
2) try to add liqudity

### Describe the issue behavior

![photo_2022-05-09_20-43-16](https://user-images.githubusercontent.com/73851144/167476318-948862b3-629a-4fca-b32a-61ef61a22187.jpg)

### BitSong Public Address

bitsong12lvzccwrpcxc426nq9nk7ajn7yayas7ee3sqxr

### Osmosis Public Address

osmo1h5htvpza3knqlsrvwka94v05fmdxe80wcaeeuc

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

**Comment by Giorgionocera** [comment]
Can you please add more information about the actions you performed?
For example, you said "An error that occurs when making a swap", but you are not on the swap page.

Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.

**Comment by keenOnFrontEnd** [comment]
I already made swap from bitsong to clay tokens, and than, when i tried to make liqudity pair BITSONG\CLAY, the eror occurs

**Comment by Giorgionocera** [comment]
This occurred due to the high volatility of the price. This is not a bug, because, you got exactly the correct error.

For this reason, it is definitely not a bug.
