### ISSUE TITLE
[Competition Bug]: UI & UX BUG

### ISSUE THREAD

**Issue by Hunterx77** [bitsongofficial/sinfonia-ui#205]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Even if I haven't confirmed the transaction, ui ux is very aggressive, and there is a message stating the transaction failed.
<img width="1440" alt="Jepretan Layar 2022-05-10 pukul 01 41 07" src="https://user-images.githubusercontent.com/91028240/167478976-ae879f57-354c-4e86-abd7-8a45a2e2fe81.png">

### Describe the issue behavior

I haven't confirmed the transaction yet after adding liquidity lobo and btsg, yet the transaction failure message displays.

### BitSong Public Address

bitsong16jv67nx5dhq0ywqgtak3435c2w00lfuag75zf5

### Osmosis Public Address

osmo1q3aekesyhucq09mmdqa063lfj2xg02v2yxzcgy

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Cannot reproduce. Can you please add more pieces of information? 
Can you provide a GIF or a video?
Thank you.

**Comment by Hunterx77** [comment]
<img width="1440" alt="Jepretan Layar 2022-05-10 pukul 01 41 07" src="https://user-images.githubusercontent.com/91028240/167497864-c5ddcef1-fff7-42b0-9856-85ef222e4b55.png">
i can’t take videos because bug only one time

A transaction failed notice comes when I try to add a liquidity pool but haven't confirmed the transaction, but the transaction is successful when I confirm it.

I believe that is simply a UX issue.

**Comment by Giorgionocera** [comment]
What do you mean with:

> I can’t take videos because bug only one time

Did it happen only once?
