### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by ditsyandrea22** [bitsongofficial/sinfonia-ui#206]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Bug Isu in Swap Tesnet In web UI

### Describe the issue behavior

isu tesnet Ui web for Swap Token
![Bitsong](https://user-images.githubusercontent.com/34813777/167481586-3239b299-b439-467c-b5d1-455528107802.png)

### BitSong Public Address

bitsong1rywhzfkg90w2qsmuk4mj5st45569r4ymvkkvkz

### Osmosis Public Address

osmo1za3unydlrx7ufw5p0vjm8uaama65fezchsqs27

### Which browser are you using?

Google Chrome

### Which is your browser version?

Crome New Update

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
I cannot understand the issue. Can you explain it in different words, please? 
Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by ditsyandrea22** [comment]
sorry, I just opened this, it seems that the redemption bug in the UI of the token being exchanged is reduced and the status is still like in the picture
there is no exchange generated, please fix it

**Comment by Giorgionocera** [comment]
You are saying that transactions status remains in broadcasting even if they are not?

**Comment by ditsyandrea22** [comment]
yes status transactions me

**Comment by Giorgionocera** [comment]
So this is a duplicate for #172
