### ISSUE TITLE
[Competition Bug]: bug price

### ISSUE THREAD

**Issue by tubax111** [bitsongofficial/sinfonia-ui#207]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Price clay on event have a bug price

### Describe the issue behavior

Please pump all coins

### BitSong Public Address

bitsong163vcdgkxtx27yadzxdsw6qcnpdlsn0rdmuw0n3

### Osmosis Public Address

osmo1466l909yje3uy28vyrvhalzzzl6mphvf8clejf

### Which browser are you using?

Google Chrome

### Which is your browser version?

10.0

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

10.0.0.1

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by tubax111** [comment]
Go

**Comment by Giorgionocera** [comment]
This issue is not complete. Can you please add more details?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
