### ISSUE TITLE
[Competition Bug]: Transaction Failing while providing liquidity 

### ISSUE THREAD

**Issue by Adegoke04** [bitsongofficial/sinfonia-ui#208]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

This happened while i am trying to add liquidity in order to earn

### Describe the issue behavior

The transaction keeps failing when providing liquidity by using maximum maximum amount of the Fan token, i.e with decimal for examply Clay: 62.5345

Not untill you use the round figure, Clay: 62

That should be check

Though... its all works very fine while used the round figure when providing liquidity 

Every other things work perfectly okay and smooth... very fast

### BitSong Public Address

bitsong12jt9fcsqax36808jz4kgawr5mhp64lh3jtqzt4

### Osmosis Public Address

osmo1l50c9lmnjj089n4kredcjrl85m9r30ap9jneme

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.41

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Failing transactions were maybe linked to high traffic generating high slippage on price (and not covering min amount).
Uploading error messages or images could be simpler for debugging.

It seems to not be a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by Adegoke04** [comment]
I think you are right... as i have tried it again 3 times and went
successful and perfect

Thank you
