### ISSUE TITLE
[Competition Bug]: GAS FEE

### ISSUE THREAD

**Issue by awfyfatahillah12** [bitsongofficial/sinfonia-ui#209]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I got a little bug in the gas fee, where there is no gas fee for doing tx, please fix it

### Describe the issue behavior

gass fee not applicable

### BitSong Public Address

bitsong14nmntx67egymc2um2qg59fj2glrx6apep3fx6a

### Osmosis Public Address

osmo1hfa0m7az25m8xymrfus38ca426ln5zwgtp95fk

### Which browser are you using?

Google Chrome

### Which is your browser version?

Versi 101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Sorry, I cannot understand your issue. Can you explain it with different words, please?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
