### ISSUE TITLE
No bug 

### ISSUE THREAD

**Issue by kkhwds** [bitsongofficial/sinfonia-ui#210]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I have done ,swap ,add lp , remove lp ,and bond lp , and I didn't find any bugs and the web is running smoothly

### Describe the issue behavior

I have done ,swap ,add lp , remove lp ,and bond lp , and I didn't find any bugs and the web is running smoothly

### BitSong Public Address

bitsong1wkvyljsxw4zfdpaetnsndhqz2pdrggl4t7ct0w

### Osmosis Public Address

osmo1jarzta83vf9mf5fdcrd3tkj4jmjnghsnm2y2uf

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Thank you for your comments.
