### ISSUE TITLE
[Competition Bug]: Swap token to osmosis

### ISSUE THREAD

**Issue by desty0dwi** [bitsongofficial/sinfonia-ui#213]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Here there is a difference when we want to transfer to tesnet osmosis. at that time we could not see our BTSG balance in assets, even though in the KEPLR wallet on the Bitsong Tesnet network there was a balance

### Describe the issue behavior

I noticed the less fast response on the tesnet. I tried several times before the balance was able to enter the account, it was very difficult for me

### BitSong Public Address

bitsong184fjmfrtn0kk5sl498595qwc20mf5ruut8qtnl

### Osmosis Public Address

osmo1ax0sl829jzxzlegrm8j6z4twvmf90zefvcager

### Which browser are you using?

Google Chrome

### Which is your browser version?

4.3

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Please can you be more specific?
Can you add images or videos of what is happening?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by desty0dwi** [comment]
This in asset 0 and in keplr 10k When i want swap to osmosis in assets

**Comment by Giorgionocera** [comment]
You need to transfer tBTSG from BitSong testnet to Osmosis one. Please, read the guide https://docs.bitsong.io/useful-guides/sinfonia-users-guide

**Comment by Giorgionocera** [comment]
This is definitely not a bug.

**Comment by desty0dwi** [comment]
see this in assets
