### ISSUE TITLE
Can't swap and solution

### ISSUE THREAD

**Issue by Dikad1866** [bitsongofficial/sinfonia-ui#217]
### Prerequisites

- [ ] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

when we first tried this testnet feature, both in swap, add liquidity, and bond, sometimes we encountered failures in the process... for the faucet problem itself there is no problem
![Screenshot_2022-05-10-01-31-34-776_com yandex browser alpha](https://user-images.githubusercontent.com/97156271/167485568-15c32cfc-4694-4354-9f18-c82a85036707.jpg)

### Describe the issue behavior

to solve this problem I try every time I want to make a transaction I have to refresh the web page,,, and after that it can be smooth and normal without any problems, thank you

### BitSong Public Address

bitsong1wqm3h0sc9zujeq4zn7ewhsvy6tgj3mcsgud5yv

### Osmosis Public Address

osmo1njmylcra25xxtcdd967wsvveuw4a7zzn22fs9y

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.88

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The first requirement for this kind of issue:

"You confirm that your bug is available through the Chrome browser accessed by a Desktop computer."

This is not verified.
