### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by azis0** [bitsongofficial/sinfonia-ui#219]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

add liquidity

### Describe the issue behavior

Nothing swap

### BitSong Public Address

bitsong1yqv8x08nupcqa826n43z4yg20a26dt8zeg2vfd

### Osmosis Public Address

osmo18t5ld6uje540awyxua8dg8f8f2dzrahc872vh0

### Which browser are you using?

Google Chrome

### Which is your browser version?

22.3.0.195

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

22.3.0.195

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
I cannot understand your issue. Please could you be more specific?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
