### ISSUE TITLE
Refactor the scrollbar

### ISSUE THREAD

**Issue by giorgionocera** [bitsongofficial/sinfonia-ui#22]
The scrollbars in the tables need to be discussed with the design.

Implementation:
![scrollbar](https://user-images.githubusercontent.com/13519292/159693771-262f5768-a3d7-4ee2-be45-eb394b968491.jpg)

**Comment by EnricoBarbieri1997** [comment]
Already changed in a previous version.

**Comment by Giorgionocera** [comment]
Thank you!
