### ISSUE TITLE
[Competition Bug]: Cross-Domain JavaScript Source File Inclusion

### ISSUE THREAD

**Issue by GalihNugraha22** [bitsongofficial/sinfonia-ui#220]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Ensure JavaScript source files are loaded from only trusted sources, and the sources can't be controlled by end users of the application.

### Describe the issue behavior

The page includes one or more script files from a third-party domain.

evidence : <script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "99f87305b82243c5bbfbcd0dcd48413e"}'></script>

### BitSong Public Address

bitsong1a0c5a287ytyklrscpaydjaerfe92e0zxjngf7u

### Osmosis Public Address

osmo1es7ch3ytg2laeall703u87agmq4lr6zdw3vw6j

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by DavideSegullo** [comment]
Duplicated #194
