### ISSUE TITLE
[Competition Bug]: Missing Anti-clickjacking Header

### ISSUE THREAD

**Issue by GalihNugraha22** [bitsongofficial/sinfonia-ui#222]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Modern Web browsers support the Content-Security-Policy and X-Frame-Options HTTP headers. Ensure one of them is set on all web pages returned by your site/app.
If you expect the page to be framed only by pages on your server then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. Alternatively consider implementing Content Security Policy's "frame-ancestors" directive.

### Describe the issue behavior

I found some bug on this website 

Problem : 
Missing Anti-clickjacking Header

The response does not include either Content-Security-Policy with 'frame-ancestors' directive or X-Frame-Options to protect against 'ClickJacking' attacks. Clickjacking is a type of attack on a website that causes the victim to accidentally go to a page they don't want to visit, by clicking on an element on a web page that has redirected/rejected malicious code. This can happen because the website can be entered / accessed via an iframe on other web pages.

So, if this issue is not resolved, it is possible that the website could be compromised when someone tries to connect the wallet, and it will connect to a fake keplr wallet connected.

### BitSong Public Address

bitsong1a0c5a287ytyklrscpaydjaerfe92e0zxjngf7u

### Osmosis Public Address

osmo1es7ch3ytg2laeall703u87agmq4lr6zdw3vw6j

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

101.0.4951.54

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by DavideSegullo** [comment]
Duplicated of #194
