### ISSUE TITLE
[Competition Bug]: Incorrect Warning on Swap Page

### ISSUE THREAD

**Issue by krtlp1** [bitsongofficial/sinfonia-ui#223]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

On Swap page, there was an incorrect warning. When i tried to swap my tokens, i took a warning about not enough asset on wallet.  
I used Chrome and repeated similar actions to understand that warning is temporary or not. I saw that this issue is not temporary, it was permanent. All details were given in next section with screenshots.

### Describe the issue behavior

While i was swapping my assets after clicking on MAX (RWNE to CLAY), i took a warning as "You don't have enough coins". It was not correct because i had enough amount in my wallet then i decided to continue to swap my coins. Although the warning that i saw, i click clicked on Swap Tokens. After a short time, transaction was completed successfully. After that i wanted to try it for different coin. When i tried it for FONTI to CLAY, i took same warning again but transaction was completed successfully. I am adding screenshots in attachment.

Report-1: Screenshots for different token swaps
Report-2: Warning differences on above and bottom part of swap **(should be clicked to MAX after token change (not enough balance) to (enough balance))**

[Bug Report_Sinfonia.pdf](https://github.com/bitsongofficial/sinfonia-ui/files/8654992/Bug.Report_Sinfonia.pdf)
[Bug Report_Sinfonia_2.pdf](https://github.com/bitsongofficial/sinfonia-ui/files/8655109/Bug.Report_Sinfonia_2.pdf)

### BitSong Public Address

bitsong1gkvq07awz9ckaw89a4mfmzs7g75nd76jgkk8uy

### Osmosis Public Address

osmo16w7ly2f8tea79hcamzu443pmt345qv85yrh8nj

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #160.
