### ISSUE TITLE
[Competition Bug]: bug

### ISSUE THREAD

**Issue by Adityaappp** [bitsongofficial/sinfonia-ui#224]
### Prerequisites

- [ ] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Using desktop mode on a mobile phone, you have to approve the transaction twice, if not twice, the confirm button won't appear, many don't know because when the popup is loading it takes a long time, so that it is successfully confirmed, we have to open a new tab and re-do the second transaction the same as the first transaction. , example : (swap) btsg-clay - Approve - loading now if you wait it will not appear the comfrim (Approve) button. I had to redo it by opening a new tab and doing the same thing it just worked because not everyone has a laptop or computer so I represent the use of mobile phones to report this problem to make it easier, maybe that's all I want to say

### Describe the issue behavior

Use Kiwi Browser and ekstension wallet

![Screenshot_2022-05-10-03-00-58-08_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/90529188/167489495-62a4efe1-4914-4ef1-9abd-830b3465fb29.jpg)
![Screenshot_2022-05-10-03-02-00-82_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/90529188/167489553-f31bb032-1dce-4f4c-a42d-a8858392d586.jpg)

### BitSong Public Address

bitsong1xx9l95aacu8z29rp09ee5d406jcf0qja5gcx7p

### Osmosis Public Address

osmo1xx9l95aacu8z29rp09ee5d406jcf0qjas6e72u

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.40

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

0.10.3

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a **Desktop computer**, not by using desktop mode on a mobile phone.

**Comment by Adityaappp** [comment]
thanks sir, but not everyone has a computer, i hope you understand ☺️

Pada tanggal Sel, 10 Mei 2022 03.37, Giorgio Nocera <
***@***.***> menulis:
