### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Awmdan1** [bitsongofficial/sinfonia-ui#225]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

when i add liquidity(deep), it often fails and i haven't found a solution..

### Describe the issue behavior

often wrong in error while broadcasting tx. this will be further in the transaction error if it is not resolved as soon as possible sir

### BitSong Public Address

bitsong1hfj4tu0quhras45pd8uplc9qz7qylm46w752ju

### Osmosis Public Address

osmo1hfj4tu0quhras45pd8uplc9qz7qylm462v4jxp

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.40

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Failing transactions were maybe linked to high traffic generating high slippage on price (and not covering min amount).
Uploading error messages or images could be simpler for debugging.

It seems to not be a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
