### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Lukmangkiem** [bitsongofficial/sinfonia-ui#228]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

very difficult to do swap, it took several times to work, when i approve, the page closes automatically, i don't know if it's a problem from sinfonia or from my browser. I hope the team can do more to develop this facility.

### Describe the issue behavior

several times trying to swap it always failed, in the end I tried to approve it again and finally it worked even though the sinfonia page was closed

### BitSong Public Address

bitsong1n27xf0p96fx8hznvm8xuq3nums97xxsvkza8rc

### Osmosis Public Address

osmo1vwjul7euvydaq2dqtlsxzxtmw3faxgpqcyexdc

### Which browser are you using?

Google Chrome

### Which is your browser version?

80.0.3987.99

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Are you able to reproduce the problem again?
Or did it happen only once?

Failing transactions were maybe linked to high traffic generating high slippage on price (and not covering min amount).
Uploading error messages or images could be simpler for debugging.

It seems to not be a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
