### ISSUE TITLE
[Competition Bug]: NavBar Blank Space

### ISSUE THREAD

**Issue by anggasec28** [bitsongofficial/sinfonia-ui#229]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

try to access your elements, after page has completely loaded. something like that:

Example code : 

    ```
window.onscroll = function () { myFunction() };

    window.onload = function () {
        var navbar = document.getElementById("topNav");
        var sticky = navbar.offsetTop;

        function myFunction() {
            if (window.pageYOffset >= sticky) {
                navbar.classList.add("sticky");
            } else {
                navbar.classList.remove("sticky");
            }
        }
    }
```

### Describe the issue behavior

I'm making a fixed navigation bar and using JavaScript to detect when the user refresh page.

after that, as soon as I try refresh page, it starts cons
![Screenshot_2022-05-10-03-04-34-36_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/90994381/167500723-4d3ee710-24ad-4b76-9d47-303e72332844.jpg)
tantly generating the same error

### BitSong Public Address

bitsong16fapt3jyuykhkhcqr0kmd9kdrymswnrv73augr

### Osmosis Public Address

osmo1gzpr7gpeey9ctaghucav9dmr3tq0gk4scl4y6r

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.73

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.

**Comment by anggasec28** [comment]
Sorry sir i don't have pc only android

Pada tanggal Sel, 10 Mei 2022 15.07, Giorgio Nocera <
***@***.***> menulis:
