### ISSUE TITLE
[Competition Bug]: Cross-Domain   Misconfiguration

### ISSUE THREAD

**Issue by zonecrypto2** [bitsongofficial/sinfonia-ui#230]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

just a suggestion:

Ensure that sensitive data is not available in an unauthenticated way (using a whitelist of IP addresses, for example).
Configure the HTTP header "Access-Control-Allow-Origin" to a more restrictive domain set, or remove all CORS headers entirely, to allow web browsers to enforce the Same Origin Policy (SOP) in a more restrictive manner. hope it can be useful

### Describe the issue behavior

A bug occurred in Cross-Domain Misconfiguration
sometimes it becomes an obstacle that makes it left to be

CORS misconfiguration on the web server allows cross-domain read requests from arbitrary third-party domains which can compromise security, using unauthenticated APIs in this domain. However, web browser implementations do not allow arbitrary third parties to read responses from authenticated APIs. This somewhat reduces the risk. This misconfiguration can be used by an attacker to access available data in an unauthenticated manner, but which uses some other form of security, such as a whitelist of IP addresses.

### BitSong Public Address

bitsong1hxdlxhfn83t2swhpauy35grqzt0ymfj00gzs4v

### Osmosis Public Address

osmo1ff2j67xwc3cuaww8vm9jsar53cwkmhq7gjlwt2

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by GalihNugraha22** [comment]
lol copy my bug reports haha

**Comment by zonecrypto2** [comment]
wkwkwkw sorry bro

**Comment by zonecrypto2** [comment]
> lol copy my bug reports haha

wwkwkwkw there are a lot of problems there, sir

**Comment by Giorgionocera** [comment]
Duplicated of #226.
