### ISSUE TITLE
[Competition Bug]: sometimes having problems connecting to the keplr wallet, I'm using android and it can't connect. I finally decided to use a PC and it went smoothly

### ISSUE THREAD

**Issue by aryaranggap06** [bitsongofficial/sinfonia-ui#232]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

sometimes having problems connecting to the keplr wallet, I'm using android and it can't connect. I finally decided to use a PC and it went smoothly

### Describe the issue behavior

for the swap, there is a fairly long delay, connecting to the keplr wallet is also difficult via android

### BitSong Public Address

evmos1dcj9tfqwtmx2hqpsq9cg4xtqk93ze5fct53lrt

### Osmosis Public Address

osmo1uy0mgwsrr7xh8j4ckz7l6m2nkn6wxzcezcgthv

### Which browser are you using?

Google Chrome

### Which is your browser version?

chrome 101.0.4951.41 and kiwi browser 101.0.4951.40

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

1.0.24

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Thank you. The issues are only related to Google Chrome Desktop instances.
