### ISSUE TITLE
[Competition Bug]: Web not working properly in keplr extension wallet on yandex

### ISSUE THREAD

**Issue by wahyudi07** [bitsongofficial/sinfonia-ui#234]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I'm using the keplr extension on yandex to participate in tesnet events, the first time I did a swap it worked but the second time the tab containing the web sinfonia was closed after I clicked on the confirmation button from the keplr extension, for that please fix it so I can immediately follow the testnet event , thank you darling.

### Describe the issue behavior

This website has a longer response time if you use an extension on a cellphone, specifically in my case the website automatically closes after I confirm the Keplr pop up for transactions

### BitSong Public Address

bitsong192tj0amx489uzr8afspd0dapa89r3auxr4pw9c

### Osmosis Public Address

osmo1tmvlchtprdp9y0dpnql2wnfsfw3rhk94dlkh3t

### Which browser are you using?

Google Chrome

### Which is your browser version?

10.0.3

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
