### ISSUE TITLE
[Competition Bug]: Delay on Transaction Track & Browser Crash

### ISSUE THREAD

**Issue by alvingreysolana** [bitsongofficial/sinfonia-ui#236]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [ ] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

An error occurred on the server detecting transaction activity. Where, many transactions are experiencing "Broadcasting", but these transactions fail.

Where, transactions that have been successful are not detected in that column. This bug causes disruption of trading activities, such as trading on the same pair repeatedly will cause the browser that is used to crash.
![Screenshot_51](https://user-images.githubusercontent.com/101128751/167505775-e8c452c0-1168-4fc4-8272-8bc65b93248b.png)

### Describe the issue behavior

This problem affects trading activity, which can cause crashes in the browser that is used.

### BitSong Public Address

bitsong1z4tjaxwd8tm5wu8d8fyva82j5f799s08j9g35a

### Osmosis Public Address

osmo190gl9xrw459gtclw5amlysfu4gkgq06fnhprfz

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #172.
