### ISSUE TITLE
[Competition Bug]: Swapping token of BTSG to D9 pair,  no D9 tokens acquired.

### ISSUE THREAD

**Issue by DauntlessLimitless** [bitsongofficial/sinfonia-ui#238]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I Swapped my BTSG testnet token to D9 token , under Pool7  (D9/BTSG). As I head over to Pool tab , for me to be able to provide liquidity, I notice that I do not acquired a D9 token. Instead of getting D9 token, what reflected on my screen is CLAY token. Even in my transaction history, the D9 and BTSG pair is missing. The transaction history that show is CLAY/BTSG instead of D9/ BTSG. 

### Describe the issue behavior

When I swap BTSG to D9, the token that I got is CLAY token as the transaction succeeded. The switching is happened between D9/ BTSG pair and turns our CLAY/ BTSG after the swap confirmation.

### BitSong Public Address

bitsong1pkdxg887gzt38h0d9k04qfy6yux98mjtjeaq0d

### Osmosis Public Address

osmo185vpcjaswc7ns2vrummfzsy0zy68e824zgw6mg

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

not applicable / n/a

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Are you sure you correctly swapped BTSG to D9? 
What I mean is: Did you give a look at what was on the swap component?

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by DauntlessLimitless** [comment]
> Are you sure you correctly swapped BTSG to D9? What I mean is: Did you give a look at what was on the swap component?

Yes.. because i wanted to make a swap in 3 different pools.. I doubled check it... and got puzzled why and how it had happened. Any way thanks for the response, I will still try to test the system.
