### ISSUE TITLE
[Competition Bug]: Jog handle is missing

### ISSUE THREAD

**Issue by Alien901** [bitsongofficial/sinfonia-ui#239]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

go to any pools, click add/remove liquidity, go to remove liquidity, 

### Describe the issue behavior

well, it has everything except the manual slider for moving without entering any percentage manually. please add the slider. 

![image](https://user-images.githubusercontent.com/6206953/167511023-dda3fd21-ce4d-4cba-9067-a1b21b767ea7.png)

it should be like this

![image](https://user-images.githubusercontent.com/6206953/167511237-90089339-0b15-455d-af7a-3aff0fb9537b.png)

### BitSong Public Address

bitsong1xxj3fmymyj39zycxerur5p0laz55wxdxk9fqjw

### Osmosis Public Address

osmo135pzc6yh5usgskvn3neuqvzatjuk57zdgs6803

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

N/A

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Thank you for your suggestion. But you filled up the wrong form. You need to submit an issue for improvements.
It is definitely not a bug.

**Comment by Alien901** [comment]
Should I re upload or it's fine right???

**Comment by DavideSegullo** [comment]
Yes, but only bugs are eligible for the competition. Improvements are always well accepted
