### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Ariefbuday** [bitsongofficial/sinfonia-ui#240]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I followed the guide when running testnet, there was an error adding liquidity.
<img width="1440" alt="Jepretan Layar 2022-05-10 pukul 05 31 17" src="https://user-images.githubusercontent.com/90925545/167510945-a626f16e-d304-40ee-a4de-2d4dd00cf1e7.png">

### Describe the issue behavior

there is a transaction failed and error broadcasting error tx

### BitSong Public Address

bitsong1zaauvw8upl6ryxff5vsv3luz5nusgc2r27vnfd

### Osmosis Public Address

osmo1vn353ufpdd9qhgah0ac7wee2gj9lwfgewhrqp7

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The issue is communicating with you some information. Maybe you did the operation on another page. Please try to refresh the page and verify if the problem is reproducible.

I think it is not a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
