### ISSUE TITLE
[Competition Bug]: WRONG CONFIGURATION OF TRANSFER OF NATIVE TOKEN(BSTG) TO OSMOSIS NETWORK BEFORE ASSESSING IN BITSONG

### ISSUE THREAD

**Issue by Reggiehub** [bitsongofficial/sinfonia-ui#241]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Before Assessing the Testnet BTSG I had to transfer the token  to Osmosis chain before it could be swapped on bitsong.  This configuration is not regular when compared to already existing Dex like junoswap.com.amd app.osmosis.zone.
 This two have their native Token juno and Osmosis respectively and when using the Dex you don't have to transfer your juno or Osmosis to the Dex as they are the native Token.  This should be reconfigured before the mainnet launch as it will save some newbies the stress of avoidable confusion. 

### Describe the issue behavior

After the transfer all the transactions was successfully but if the protocol can be reconfigured so as to correct the transfer of native Token of the dex

### BitSong Public Address

bitsong1e2rgjq3wuxfj5jwsxr2ptvzjhpppjvtgwpz9tm

### Osmosis Public Address

osmo1gg8vheysqwkcl60csltecfx9tuvge9e9wl6nsf

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This is definitely not a bug. The instructions are provided in the guide.
The transfer is required by the structure of the platform.
