### ISSUE TITLE
[Competition Bug]: when i want to add liquidity pool

### ISSUE THREAD

**Issue by Notme7138** [bitsongofficial/sinfonia-ui#244]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I always repeat the experiment that I have done in BTSG/D9 swap and always try to load repeatedly until it works, and when I add liquidity in Clay/BTSG I always do it every minute until all the transactions that I have done are done and I do that  come back until you can

### Describe the issue behavior

when i want to add liquidity pool in clay/btsg it always fails even though my clay/btsg has 50% 50% it always fails, and when i swap btsg/d9 it always fails

### BitSong Public Address

bitsong13wrhm4r3nt9p3hey28a0vcdld26hgsxtrkgy7j

### Osmosis Public Address

osmo1upn5z7mh83z4tpdht2v98lgywnm0znnyp4q6qu

### Which browser are you using?

Google Chrome

### Which is your browser version?

77.0.3865.120

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

2.0.2

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Failing transactions were maybe linked to high traffic generating high slippage on price (and not covering min amount).
Uploading error messages or images could be simpler for debugging.

It seems to not be a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
