### ISSUE TITLE
add a calculator tool in the pools menu[Competition Bug]: 

### ISSUE THREAD

**Issue by KangDanKer** [bitsongofficial/sinfonia-ui#245]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

![Screenshot - 2022-05-10T064722 163](https://user-images.githubusercontent.com/78604911/167517529-b681ac95-feac-4c44-90f4-12830373f629.png)

### Describe the issue behavior

I think it would be better if the pools menu added a calculator feature, because it would make it easier for newbies or other users to find out the apr and the estimated reward that he would get if he joined the pools. so if a user wants to join a pool he can check first by
-Enter the amount of funds that he will join the pools
-choose the time (days) how long he will join the pools
then comes the estimated reward that he will get with the funds and time he chooses. I hope this helps a little to improve the Sinfonia web, thank you.
![Screenshot - 2022-05-10T064722 163](https://user-images.githubusercontent.com/78604911/167517303-d2bd6c90-07b6-42d4-97a2-74d2d0f93161.png)

### BitSong Public Address

bitsong16k4prt559040xtd83z9hh5k7m72lfergyjvg7q

### Osmosis Public Address

osmo18tarmvpeyckhsrngvduxv37u6w9l3gzswjwmh9

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Thank you for your suggestion. But this is not a bug. You should fill in the template to propose a new enhancement.

**Comment by KangDanKer** [comment]
oh yah iam sorry , I chose the wrong category

**Comment by DavideSegullo** [comment]
But only bugs are eligible for the competition. Improvements are always well accepted, if you wanna report it you should make a new issue as enhancement
