### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Utama1902** [bitsongofficial/sinfonia-ui#246]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I Suggest To Check The Entire Bitsong Page.  Even though this is out of topic, because what is being discussed is a Testnet page, there must still be improvements in the Wallet menu

### Describe the issue behavior

I found a Bug On the Web https://wallet.bitsong.io/#/

When I checked on Bitsong Web Wallet, I clicked on 'Keplr Browser Extension', but after that I got stuck there
I've Connected Wallet Keplr, But After That I'm Stuck

![Screenshot_2022-05-10-07-07-35-466_com yandex browser](https://user-images.githubusercontent.com/51355134/167518282-e945af50-d8f2-421c-8903-fb42953a355e.jpg)

I waited for a few minutes and still stuck, things didn't change

![Screenshot_2022-05-10-07-11-00-971_com yandex browser](https://user-images.githubusercontent.com/51355134/167518365-4dfb995c-24db-4449-ab74-e9cbbaa94bb7.jpg)

See the difference in the hours

### BitSong Public Address

bitsong184m6ggfar0026vw4wdkkxylc7mhejhu37224fr

### Osmosis Public Address

osmo1yyvnancpp0qnx9vquvehrytueu02a03v0chv04

### Which browser are you using?

Google Chrome

### Which is your browser version?

95.0.4638.74

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This issue is not related to Sinfonia. Add it to the wallet dapp repo.
Moreover, the wallet is not reachable during the Sinfonia competition. This is the reason for your problem.
