### ISSUE TITLE
[Competition Bug]: Bitsong balance doesn't appear when Connect

### ISSUE THREAD

**Issue by Fathul24** [bitsongofficial/sinfonia-ui#247]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

When I connect the Bitsong Wallet, the Balance on the Sinfornia Platform is not detected or 0 even though I have connected the wallet but it's still 0

![Screenshot_2022-05-10-06-43-56-34_16c08c2f05c0b6a683890ee237cb1d6f](https://user-images.githubusercontent.com/86880066/167518192-bbee8684-6041-4bcd-b7e5-dcfa9196459c.jpg)
![Screenshot_2022-05-10-06-44-00-81_16c08c2f05c0b6a683890ee237cb1d6f](https://user-images.githubusercontent.com/86880066/167518197-14149d2c-7106-4b35-a0fb-907061b98283.jpg)

### Describe the issue behavior

Yes, the problem is that Bitsong Balance does not appear when it is Connected. Maybe how to fix it should be refreshed or what I don't know. What I did was close the app and reconnect it,and sometimes that method doesn't work so I have to keep refreshing for the Balance to appear.

### BitSong Public Address

bitsong19a87x7qdxyldgl79fsey8eq3hl72ljq59jtd65

### Osmosis Public Address

osmo1vmfs0r4yfw4sxlanmpvta9dea8jksy60209wuz

### Which browser are you using?

Google Chrome

### Which is your browser version?

Yandex Browser Alpha : Version : 22.1.7

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
