### ISSUE TITLE
[Competition Bug]: UI BUG

### ISSUE THREAD

**Issue by restucode** [bitsongofficial/sinfonia-ui#249]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

First issue, when I'm trying to swap from BTSG to CLAY with MAX token total

Then, the error message that is displayed always appears even though the number of tokens meets

A more detailed explanation in the section explain the behavior of the problem

The second issue, I continue the transaction until a transaction notification pop up appears, if on the dark mode display, the writing is still legible, when I change it to light mode the transaction pop up position still appears, the text is not legible

### Describe the issue behavior

You can see in the video below, I tried to make a transaction from BTSG tokens to CLAY with the total token being maximized

Then, I changed the pair to CLAY to BTSG with a maximum of tokens too.

Because the price of CLAY tokens changes, the price of the pair will automatically change

I changed the pair again to BTSG to CLAY, the total BTSG needed will also change

Show error due to lack of BTSG token

I delete some decimal numbers, then I press the MAX button again

The error message should not appear because I have reset the number of tokens to the same as I have

However, the error still appears. Plus, when the Swap Tokens button, transactions can be executed with the error message still appearing.

When I reject the transaction, a pop up error transaction appears in dark mode, when I change it to light mode with the pop up error position still on, the writing on the transaction error cannot be read in light mode

https://user-images.githubusercontent.com/61130384/167521192-e6609b63-d6b8-4fac-8bfa-7bfdfed4c19c.mp4

### BitSong Public Address

bitsong1qz6gmw6367qt8070n8l7k9azp5jlz0mgmcuwj9

### Osmosis Public Address

osmo1jfcdw8zwzsv0dtwfu3rvm2cnmryrvskh7pjjms

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Please, next time create an issue for each "problem".

I'll respond to you by points:
1. Duplicated of #160 
2. Duplicated #180

**Comment by restucode** [comment]
Thanks for the response,
That became my learning when I wanted to send an issue.

Is the issue that I created is not counted?

**Comment by Giorgionocera** [comment]
It is not ok to participate in the "**bug competition**". But you need to create a new one only if you see real bugs.

**Comment by restucode** [comment]
Oh okayy, thanks for the information. I will learn again to find the real bug in another case
