### ISSUE TITLE
MINIMUM ASSETS WARNING

### ISSUE THREAD

**Issue by Siven-cyber** [bitsongofficial/sinfonia-ui#257]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

First I want to add liquidity tokens to the pool in the amount of more than $100, then I want to add again a smaller amount with a valuation of $1 because I get the result of bound tokens, but it's having a problem warning that the asset I added is less than the minimum. I tried again on my other token with $4 valuation and it worked. The crux of the problem is the uncertainty of what is the minimum asset that can be added to the pool

### Describe the issue behavior

Hello,
I found a flaw on your website, where on the pools page it doesn't state what the minimum single asset or multiple asset value that we can add to liquidity is so we don't know what the value is. This is very important, especially I want to redelegate my small assets to be re-entered the pool, and even better, the auto compound feature can be added as a result of the bounding token.

### BitSong Public Address

bitsong1hcfj50fcazw05awq04k6t62szhgx3aycj9gmp8

### Osmosis Public Address

osmo1gr9t7qtm3hwfd6twwe8fx5zzjh5e406ycqznec

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Can you paste the errors you got, please?

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by Siven-cyber** [comment]
> Can you paste the errors you got, please?

![image](https://user-images.githubusercontent.com/70112921/167624198-ca9b80bf-a8c2-4077-ad63-f2fd2a08cf95.png)

**Comment by Siven-cyber** [comment]
![image](https://user-images.githubusercontent.com/70112921/167624329-0fa55ef8-8fcb-4746-8ae4-02419fab3783.png)

**Comment by Siven-cyber** [comment]
![image](https://user-images.githubusercontent.com/70112921/167624554-b7289b62-49e2-4449-9bbd-7dffce4a6b31.png)

**Comment by Giorgionocera** [comment]
**The images you posted are not related to the issue you wrote as a description.**
The last image seems to be a temporary bug. Are you able to reproduce it?
