### ISSUE TITLE
Use graph instead of static image

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#26]
In the pool PDP, the graph on the top left I now implemented as an image, while the compositions inside the box are dynamically generated through a progress bar. We need to implement a similar component for the graph. 
We can use the progress bars as well.

Implementation:
![static-graph](https://user-images.githubusercontent.com/13519292/159710010-171fe07d-3cd6-4309-b78f-09eb0065ef4e.jpg)

**Comment by Giorgionocera** [comment]
Related issue: #34

**Comment by EnricoBarbieri1997** [comment]
Resolved in another issue #34
