### ISSUE TITLE
[Competition Bug]: web design and add new options 

### ISSUE THREAD

**Issue by mehdisky99** [bitsongofficial/sinfonia-ui#260]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

![Screenshot (9)](https://user-images.githubusercontent.com/79857890/167526839-3ef44471-714f-4ae1-b5a3-0a45bc44c3b9.png)

amazing testnet sir this is very simple and easy I really like it I hope the project is a success and I hope to get feedback.

### Describe the issue behavior

Add farm option and stake to the site. The design of the site looks old and I think you should change it and update the site. Add the option to disconnect wallet. thanks for everything.

### BitSong Public Address

bitsong174jjknea9pjqp00vnsa47s5tqq9r4s9vukqpng

### Osmosis Public Address

osmo1ymk2uh6rd87lm3w6r2gcgzcq044lnnwd3027lr

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This is definitely not a bug.
