### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Pejuangrupiah1** [bitsongofficial/sinfonia-ui#261]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

when I was doing testing, I found a problem / bug, namely when I wanted to approve the transaction I did, an error occurred so the transaction I did did not work

### Describe the issue behavior

After I observed and tried to repeat it again, finally I was able to make a good transaction and no more problems

### BitSong Public Address

bitsong1q20rrsc5vm7megkxuklefx7zykhvhqxpgzxwq5

### Osmosis Public Address

osmo1nm4gajtzl35yx0exm2szyf7wkv9pswajkva7rw

### Which browser are you using?

Google Chrome

### Which is your browser version?

22.5.1.100

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

10.2.1

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Failing transactions were maybe linked to high traffic generating high slippage on price (and not covering min amount).
Uploading error messages or images could be simpler for debugging.

It seems to not be a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
