### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by BTYXXX09** [bitsongofficial/sinfonia-ui#263]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I think we should improve the UI/UX in terms of smooth transaction, because sometimes I complete the transaction but the UI hasn't been updated. So I think we should need an update for UI/UX.

### Describe the issue behavior

I've tried several features on the platform and there are some bugs/lacking features that haven't been added I hope in the future you can add this feature & fix BUGs on mobile too so that all users are comfortable when accessing your platform

The web application is quite slow and frustrating. lots of pending transactions and unresponsive ui/ux, sometimes i get bugs like button can't be clicked or my balance doesn't show , And there's a little bug in swap part where token price doesn't match market price. Another minor issue is that you have to wait a while before making the swap because the swap section doesn't respond quickly.

### BitSong Public Address

bitsong172lw0jyv2ah8f22k40lrc6fv636jv0l7sh2zjk

### Osmosis Public Address

osmo172lw0jyv2ah8f22k40lrc6fv636jv0l759t6xt

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The speed of the transactions depends on the fact that this is a simple testnet environment.
This is definitely not a bug.
