### ISSUE TITLE
[Competition Bug]: Error to connect wallet

### ISSUE THREAD

**Issue by valelengdiez** [bitsongofficial/sinfonia-ui#264]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

the simple bug or issue is to slow at failed transaction and cannot connect in keplr sometimes

### Describe the issue behavior

this testnet is nice to use but sometimes error in to connect walllet and transaction

### BitSong Public Address

bitsong1cdwwmt3nzcneh64ffu748m46lxe96qas8ucej5

### Osmosis Public Address

osmo1056r3px282u09dv8exds7jeuznf8zxlkkdg9uv

### Which browser are you using?

Google Chrome

### Which is your browser version?

10.0.1

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

0

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Failing transactions were maybe linked to high traffic generating high slippage on price (and not covering min amount).
Uploading error messages or images could be simpler for debugging.

It seems to not be a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
