### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by wahyu387** [bitsongofficial/sinfonia-ui#268]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

If do some swap in Dapps,sometime Rejected Confirmating transaction coming
![rejected](https://user-images.githubusercontent.com/45675582/167532306-e9ffe85f-9382-4a59-b424-4d0f57be604e.png)

Visit This for evidence
https://drive.google.com/drive/folders/1ZDqF9M46bwr3TvvqdeysCy0g4Wr6shrA

### Describe the issue behavior

in coming transactions rejections befor transactions begun,and after that transactions complate

### BitSong Public Address

bitsong1nzqnxhscfcsyaq5gyxgcj98zwec4qd5uyl6ket

### Osmosis Public Address

osmo16ckn0yvaclvqz3f6vse0ap7z3fqrp6w40qrz5t

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Waiting for access to see evidence

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
