### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by alif313** [bitsongofficial/sinfonia-ui#269]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

1. Bitsong balance is not shown

2. There are 2 errors when swap bitsong into clay

3. Swap delay transaction need more than 1,2 minute

### Describe the issue behavior

1. Bitsong balance unreaded automatically on sinfoni, to  show the balance I must re-logout and reconnect then I have to wait for 10 minutes before it shown. Before there is a bug, balance will show automatically on sinfoni and I can see my balance easily.

2. There are 2 errors when I try to swap bitsong into clay in nominal 10000, whereas my balance is 10170 btsg and my fee is more than enough. Before there is a bug, all transactions run with no     
problem and fast also clear and normally. You can check my transaction on my btsg tesnet wallet : bitsong15revdrn0hcy48xg30kfcw0cka3hhuzuyusz2pf

3. Swap delay transaction need more than 1,2 minute from approve process. Usually it just take 1 minute.

![Screenshot_2022-05-10-09-25-35-55_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/19809267/167532839-50d79bdd-3749-4be4-80c8-05315679f108.jpg)
![Screenshot_2022-05-10-08-07-05-11_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/19809267/167532847-2e0d0b29-f56c-475e-9534-e1db66967914.jpg)
![Screenshot_2022-05-10-00-34-07-99_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/19809267/167532852-a96b89dc-be94-4ac2-b642-9b7fa7ceef6b.jpg)

### BitSong Public Address

bitsong15revdrn0hcy48xg30kfcw0cka3hhuzuyusz2pf

### Osmosis Public Address

osmo15h7us03xxk9d5n5yvnq0ydlqd8rme4mgjm5k0k

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.40

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
