### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Awasskj** [bitsongofficial/sinfonia-ui#270]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

The balance cannot be detected by the web, Even though you have connected to a Kepler wallet

### Describe the issue behavior

've tried several features on the platform and there are some bugs/lacking features that haven't been added I hope in the future you can add this feature & fix BUGs on mobile too so that all users are comfortable when accessing your platform

The web application is quite slow and frustrating. lots of pending transactions and unresponsive ui/ux, sometimes i get bugs like button can't be clicked or my balance doesn't show , And there's a little bug in swap part where token price doesn't match market price. Another minor issue is that you have to wait a while before making the swap because the swap section doesn't respond quickly.

### BitSong Public Address

bitsong1tvg5s6xh0t6pylcs4vzg94j3s7tj8sqxzks6dy

### Osmosis Public Address

osmo1kpm7lg459m5phpkw6k63zw8enwtqnlvfpgyll6

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.41

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #263
