### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by sonyanang** [bitsongofficial/sinfonia-ui#271]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

swap problem

### Describe the issue behavior

hello sir, from what I'm doing in Sinfonia testnet, I found a bug in swapping btsg pairs with adam clay if you swap with btsg nominal which is big enough above 5000 btsg, thank you

### BitSong Public Address

bitsong16w3wp48d2dp5hp7k5q8w4sxfl0eptcu4dwzmlm

### Osmosis Public Address

osmo13vytcvlawtk2e5kfsx4g4u9lv5jcdttrpg397k

### Which browser are you using?

Google Chrome

### Which is your browser version?

100

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

I don't use the ledger version

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Please can you be more specific? Can you add images or videos?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by sonyanang** [comment]
hello sir, I can't show pictures or videos, because my btsg is not enough 5000+, because I have fully tied up all my assets, and when I untied I have to wait 24 hours first while the time you gave is only until 12 utc and it is not enough to restore my unbonding assets, my assets have not returned, and if my unbound assets have returned before 12 utc have more than 5000 btsg I will try to show the swap bug in the form of videos or images, thank you sorry if there are words wrong in speech

**Comment by DavideSegullo** [comment]
Yes, ok don't worry, we'll wait for you

**Comment by sonyanang** [comment]
I haven't found the bug anymore, sir, maybe it's been fixed, but when I first tested the pair, an error occurred and I didn't have time to record it, to the moon BTSG and fantoken,thanks
