### ISSUE TITLE
strange numbering changes on fantokens page when trying to sort by token, symbol, price and marketcap

### ISSUE THREAD

**Issue by Siven-cyber** [bitsongofficial/sinfonia-ui#272]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I want to see the order of tokens by symbol, price and market cap.

I want to see the order of tokens based on the order of token symbols, so I clicked on the SYMBOL column which should display a list of tokens in order A to Z. The sorting worked fine but the number on the left side became irregular, the number on the left should still start from 1 to 11.

### Describe the issue behavior

This also happens when I want to sort tokens based on price and marketcap.
The crux of the problem is that the number on the left must be kept in place and not move when I want to sort tokens by symbol, price, and market cap.
Thank you dev
I hope this project is successful and better with what I suggest

### BitSong Public Address

bitsong1hcfj50fcazw05awq04k6t62szhgx3aycj9gmp8

### Osmosis Public Address

osmo1gr9t7qtm3hwfd6twwe8fx5zzjh5e406ycqznec

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by Siven-cyber** [comment]
done sir, sorry about that

**Comment by Siven-cyber** [comment]
> Please write it in english.
> 
> Thank you.

done sir sorry about that

**Comment by Siven-cyber** [comment]
![image](https://user-images.githubusercontent.com/70112921/167608077-5b495dcf-cad1-42cf-992b-410560238aa8.png)

**Comment by Siven-cyber** [comment]
Done sir please check it again, sorry about my language

Pada tanggal Sel, 10 Mei 2022 16.18, Giorgio Nocera <
***@***.***> menulis:

**Comment by DavideSegullo** [comment]
It isn't a bug, the number on the left is the ranking position based on market cap, it's a number based on that and not the table order
