### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by yessskau11** [bitsongofficial/sinfonia-ui#275]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

problem swap pair BTSG-CLAY

### Describe the issue behavior

hello sir, from what I'm doing in Sinfonia testnet, I found a bug in swapping btsg pairs with adam clay if you swap with btsg nominal which is big enough above 5000 btsg, thank you.....

### BitSong Public Address

bitsong1psf3nz2g0m9u8c3pdz44a3n67vh6ctscq3nrgl

### Osmosis Public Address

osmo1re2jh9ecnzjah0s29f7ldc6920lczmnj2yl9fr

### Which browser are you using?

Google Chrome

### Which is your browser version?

100

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Can you please be more specific? Can you add videos or images?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by yessskau11** [comment]
maaf sir, hello sir, can I display video images, because my btsg is not enough 5000+, because I have fully tied up all my assets, and when I release all my assets I have to wait 24 hours first, before the time you gave until the hour 12 utc and it's not enough to restore my assets

**Comment by DavideSegullo** [comment]
Yes, ok don't worry, we'll wait for you
