### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by tancap11** [bitsongofficial/sinfonia-ui#276]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

SWAP PROBLEM
### Describe the issue behavior

hello sir, from what i did on Sinfonia testnet, i found a bug in exchanging btsg pairs with adam clay if you exchange with btsg a fairly large nominal above 5000 btsg and an error occurs, thanks sir

### BitSong Public Address

bitsong12kfg05xqw3cgvjt9g60uqtm73q89uhgh44rn54

### Osmosis Public Address

osmo16jgyqnj77wh2vstukwys6qw0dw9hlwu83g652z

### Which browser are you using?

Google Chrome

### Which is your browser version?

100

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #275

**Comment by tancap11** [comment]
sorry sir,I will change my report and find a bug
