### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by visky2001** [bitsongofficial/sinfonia-ui#277]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Dega transactions often fail at the time of degelation or stake, my advice is to fix the website so it doesn't happen again and so it can be relied on

### Describe the issue behavior

Dega transactions often fail at the time of degelation or stake, my advice is to fix the website so it doesn't happen again and so it can be relied on

### BitSong Public Address

bitsong1lg4rpugvk9jxhwy8nyllndcmaxls7mqjups37z

### Osmosis Public Address

cosmos1sz9ncvxwu28uh9nygmxpmgmhlht28qewp9mp0d

### Which browser are you using?

Google Chrome

### Which is your browser version?

22.5.1.100

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
You cannot delegate or stake through Sinfonia platform. This issue is not valid.
