### ISSUE TITLE
[Competition Bug]: Liquidity balance not showing

### ISSUE THREAD

**Issue by yogaeka1707** [bitsongofficial/sinfonia-ui#280]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I have swapped and added liquidity but the liquidity balance is not listed, only apr

### Describe the issue behavior

Not showing liquidity balance provide
![Screenshot_2022-05-10-10-31-09-285_com yandex browser alpha](https://user-images.githubusercontent.com/61999930/167538049-06ab6627-88a8-4af6-90bd-d87bec52ab13.jpg)

### BitSong Public Address

bitsong13azvf2stmhtf38e0ps42pr5tfrtv0j9jcztjer

### Osmosis Public Address

osmo1pzaf6ehws7qfgt0s7tleyy49sr2jcpu7zgr8qc

### Which browser are you using?

Google Chrome

### Which is your browser version?

92.0.4515.131

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

-

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
