### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by hdr2804** [bitsongofficial/sinfonia-ui#281]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

![Uploading IMG_20220510_104235.jpg…]()

### Describe the issue behavior

Cannot change slippage

### BitSong Public Address

bitsong1jtzce2sr7m5rxf6z7a2m84my3cmcngl6s0wmvs

### Osmosis Public Address

osmo182p3wfmyu5x229jwzuwvzhppsmkg6ag0sctqfa

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.41

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
No image is available. Could you provide some of them, please?

Thank you.

**Comment by hdr2804** [comment]
![IMG_20220510_104235](https://user-images.githubusercontent.com/82568857/167605852-a11a9cf1-8415-4ac2-82c4-4ca8a218e8ed.jpg)

**Comment by DavideSegullo** [comment]
Please, explain the error or we'll close the issue

**Comment by Giorgionocera** [comment]
You are reporting an issue from your mobile. The requirements are clear:

"You confirm that your bug is available through the Chrome browser accessed by a Desktop computer."
