### ISSUE TITLE
eror page[Competition Bug]: 

### ISSUE THREAD

**Issue by yazidwe** [bitsongofficial/sinfonia-ui#282]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I don't know why this happens, but it's a little annoying for the quality of web use on Sinfonia,
try if something like this happens to be fixed immediately because it is very influential for other people who are just learning about crypto
the table looks failed but it's a success, even though my internet condition is stable and there are no disturbances,
after i refresh normally like at the beginning

[https://testnet.sinfonia.zone/assets](url)

### Describe the issue behavior

just fix it right away maybe it's because of server problems because of the capacity of people trying to interact with this testnet

![bug sinfonia](https://user-images.githubusercontent.com/85462199/167539953-c19a891d-5915-426f-a7ab-68ffb88e92d3.png)

### BitSong Public Address

bitsong1cly0xf5yydc2n3qvj65cmex9mw08kgy8gnmtzy

### Osmosis Public Address

osmo1c27pzk7pxzv3x7asksqgsveawrdghm8t276r8n

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

101.0.4951.54

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This was a temporary issue not strictly linked to Sinfonia. Thank you for this report, but as I said, it is not a matter of Sinfonia.
