### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by ronaya2001** [bitsongofficial/sinfonia-ui#283]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

why do you always have problems in swap/staking/farm transactions even though the internet is good, the website crashes? I have a problem with the transaction

### Describe the issue behavior

why do you always have problems in swap/staking/farm transactions even though the internet is good, the website crashes? I have a problem with the transaction

### BitSong Public Address

bitsong1audafuz2y4asn9grptawch9n7ek54rztap8r9t

### Osmosis Public Address

cosmos1vg0v20grlxvmmy0vwqvz25vyh9xyhas68zc09k

### Which browser are you using?

Google Chrome

### Which is your browser version?

22.5.1.100

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Failing transactions were maybe linked to high traffic generating high slippage on price (and not covering min amount).
Uploading error messages or images could be simpler for debugging.

It seems to not be a bug.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
