### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by redlupus** [bitsongofficial/sinfonia-ui#284]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

When i try to swap BTSG - N43 Records, the fantoken column is blinking

Failled trancaction in Pool #10 ENMODA/BTSG

Failled transaction in Pool #9 CLAY/BTSG

2 time failled transaction in Pool #8 FASANO/BTSG

Failled transaction in Pool #5 LOBO/BTSG

### Describe the issue behavior

https://user-images.githubusercontent.com/83372126/167542529-7d3fd73c-27e8-43a8-ba83-c029eaa6c675.mp4
When i try to swap BTSG - N43 Records, the fantoken column is blinking

![Screenshot_20220510_012240](https://user-images.githubusercontent.com/83372126/167542811-ef943f5d-0e5e-4a79-a7ff-f7f99165b042.jpg)
Failled trancaction in Pool #10 ENMODA/BTSG

![Screenshot_20220510_012645](https://user-images.githubusercontent.com/83372126/167542945-b47a07d0-6227-40a0-a70e-f11e49aeffb2.jpg)
Failled transaction in Pool #9 CLAY/BTSG

![Screenshot_20220510_012938](https://user-images.githubusercontent.com/83372126/167543014-bd86c053-b802-4fc9-b9ae-b46333b635c3.jpg)
![Screenshot_20220510_013145](https://user-images.githubusercontent.com/83372126/167543055-17e1987e-7eef-4133-841e-50ce2bfef723.jpg)
2 time failled transaction in Pool #8 FASANO/BTSG

![Screenshot_20220510_014253](https://user-images.githubusercontent.com/83372126/167543122-59e7fe32-d0a6-41e9-a809-c5d293d648bd.jpg)
Failled transaction in Pool #5 LOBO/BTSG

### BitSong Public Address

bitsong1w5uh0tlrtzph3tk3rzal4gryewhmp4fkz0t54p

### Osmosis Public Address

osmo15rm783ssfvu6dp9uu38a6553526zyje32t9mxd

### Which browser are you using?

Other

### Which is your browser version?

22.5.1.102

### Which kind of device are you using?

Mobile

### Are you using a ledger?

No

**Comment by DavideSegullo** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
