### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by nayapurnomo** [bitsongofficial/sinfonia-ui#285]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Simple UI, and very easy for new users
Hopefully in the future there will be an application version available

### Describe the issue behavior

no serious problems, the best team with this new breakthrough and I like it

### BitSong Public Address

bitsong10vqd8687pn2cf9yjrj0vg9d63cr6m4eyyq34ea

### Osmosis Public Address

osmo13z8cd4mxh00laza2ju3kfya4pnjfv600yfhtuq

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by DavideSegullo** [comment]
Thank you for your feedback!
