### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by rangerblack** [bitsongofficial/sinfonia-ui#287]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I checked the wallet, chain testnet double 

### Describe the issue behavior

If I connet, chain show double

### BitSong Public Address

bitsong1wgrcpr50e0mxlfl36zztdywrkhu9pghu32td84

### Osmosis Public Address

osmo1utzpey5kazpst0304g0xcycq34m3a6rm2xndjy

### Which browser are you using?

Google Chrome

### Which is your browser version?

 22.3.6

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules[
![Sinfonia](https://user-images.githubusercontent.com/85515794/167635206-0235c3cf-643b-4aab-a8ea-e9749f28c87a.PNG)
](url)

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by rangerblack** [comment]
> If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

Please check, I sent the images

**Comment by DavideSegullo** [comment]
It's a bug, you have two "bitsong testnet" chains due to a diffent chain ids, it's fine

**Comment by rangerblack** [comment]
> It's a bug, you have two "bitsong testnet" chains due to a diffent chain ids, it's fine

Okay
