### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Abcdefuckyoi** [bitsongofficial/sinfonia-ui#289]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Bitsong's tesnet wallet app should not be needed because Keplr can reach all applications in its ecosystem. as we noticed, when i start testnet, the bitsong testnet wallet cannot be accessed, but keplr still works fine. although in this case, Bitsong still wants to have its own wallet.
For fan tokens. Is the fan token market cap already real? even they are still in the "coming soon" stage. In my opinion, it's better to just make a simulation for testnet than attach a fan token status that even testnet users don't understand further about their status. because the testnet users who really understand about LP will analyze it first.

### Describe the issue behavior

The slippage is very large, it would be nice to reduce it because we know the ecosystem that stands in the cosmos seems cheap. to fix it in mainnet later
when doing LP, it would be nice to add an automatic percentage feature, to avoid manual calculation to the user. Example: 25%, 50%, 75%, 100%. it will really help the user's access speed.
for the asset feature, it would be nice to add the assets (profit) that we get from each LP. so users know their earnings from each epoch automatically.

### BitSong Public Address

bitsong15cs65swdwrqr57re4835dxp2ya56uc7zexceck

### Osmosis Public Address

osmo15cs65swdwrqr57re4835dxp2ya56uc7za5epvt

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

No response

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Keep in mind that this is a bug report. 
The wallet dapp is not related to Sinfonia. 
This is only a testnet-based simulation. All data are not real money (market cap included).

If you want to propose an improvement, use the correct issue template.

**Comment by Giorgionocera** [comment]
Duplicated of #288
