### ISSUE TITLE
[Bug]: history swap

### ISSUE THREAD

**Issue by Dheni1608** [bitsongofficial/sinfonia-ui#290]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

![Screenshot_2022-05-10-13-29-34-403_com yandex browser alpha](https://user-images.githubusercontent.com/88625421/167563009-e3285cdf-0e38-4ed4-b553-ee4e2dd8c514.jpg)

![Screenshot_2022-05-10-13-29-26-662_com yandex browser alpha](https://user-images.githubusercontent.com/88625421/167563028-13c58efa-99f1-45e9-b6b6-8a37fc9d50bc.jpg)

### Describe the issue behavior

I exchanged Bitsong to another coin but the history which only reads the other three histories is not read

### BitSong Public Address

bitsong1su3psgflcegxa552spvz7j03jxs9ywesgern35

### Osmosis Public Address

osmo1luj4cdp8n4wkw0wrrw7jac20tw3lrerkx7qnzz

### Which browser are you using?

Other

### Which is your browser version?

22.36

### Which kind of device are you using?

Mobile

### Are you using a ledger?

No

**Comment by Giorgionocera** [comment]
From your screenshot, it is possible to see you also swapped BTSG in CLAY.

This is definitely not a bug.
