### ISSUE TITLE
[Competition Bug]:aprove transaksion closing link

### ISSUE THREAD

**Issue by KhoirulSodiq** [bitsongofficial/sinfonia-ui#291]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I've swapped from bitsong to adam klay also vice versa and swap fari bitsong to vibra and many more i swapped from small to large but there is one drawback every transaction aprobe links out by itself even small and large transactions that's all the bugs I get for in the future, hopefully the Bitsong party fix the bug my data Twitter https://twitter.com/KhoirulSodiq 
bitsong address
bitsong1yrhgtgyg89v020r2r0y6s0mjgkvzdeeqz0t7gu 
osmo 
osmo1xmkn556qmwzc03vhej6r4hjedxrw65wqnaemdd

### Describe the issue behavior

I've swapped from bitsong to adam klay also vice versa and swap fari bitsong to vibra and many more i swapped from small to large but there is one drawback every transaction aprobe links out by itself even small and large transactions that's all the bugs I get for in the future, hopefully the Bitsong party

### BitSong Public Address

bitsong1yrhgtgyg89v020r2r0y6s0mjgkvzdeeqz0t7gu

### Osmosis Public Address

osmo1xmkn556qmwzc03vhej6r4hjedxrw65wqnaemdd

### Which browser are you using?

Google Chrome

### Which is your browser version?

10.0.1

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

10.0.1

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Sorry, can I ask you to better explain the issue?

Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.

**Comment by KhoirulSodiq** [comment]
when I made a transaction and when I approved the wallet, the web tasi came out by itself sir. so I use 2 web tabs. that's the only weakness, my suggestion in the future is that the web tab doesn't close

**Comment by Giorgionocera** [comment]
Web tabs should not close themselves. Can I ask you to add a video about it?
Thank you.

Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.

**Comment by Giorgionocera** [comment]
You again did not upload evidence. This issue can be cosed.
