### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Hanan792p** [bitsongofficial/sinfonia-ui#292]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

why do i have the same two chains in my wallet. then why can't I make transactions with a nominal MAXS. if i do swap or add liquidy with MAX then it always fails. please fix. for the asset feature, it would be nice to add the assets (profit) that we get from each LP. so users know their earnings from each epoch automatically.

BITSONG TESNET ADDRES : bitsong1643xfu3s6c4rt94qrah70qhk0xut93au7vjvup
OSMO TESNET ADDRES : osmo1lck0fgw7pf09la5xp0p2wph5zqhd5p637k8typ

### Describe the issue behavior

two wallet chains on the same wallet, max transactions and reduce the amount of LP

### BitSong Public Address

bitsong1643xfu3s6c4rt94qrah70qhk0xut93au7vjvup

### Osmosis Public Address

osmo1lck0fgw7pf09la5xp0p2wph5zqhd5p637k8typ

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

10.0.1

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Sorry I cannot understand your issue. Can you please attach images or videos?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by Hanan792p** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/87491080/167651081-a6826b69-f22c-4d3c-80dd-7175c9f393fa.jpg)

**Comment by Hanan792p** [comment]
![Screenshot (68)](https://user-images.githubusercontent.com/87491080/167651888-64f6a9ca-401e-447e-82ea-eb3f9a2123e0.jpg)

**Comment by Hanan792p** [comment]
![Screenshot (68)](https://user-images.githubusercontent.com/87491080/167652012-0558b0a1-01fe-48b6-a512-3b7373d888f7.jpg)

**Comment by DavideSegullo** [comment]
You have two bitsong testnet because you have the old one too (different chain id).

Mintscan doesn't work because it's a testnet, it only works on mainnet.

Transaction can fail due to a network congestion, because we're on a testnet
