### ISSUE TITLE
[Competition Bug]: always failed when bridge from sinfonia to osmosis

### ISSUE THREAD

**Issue by ardiansajen** [bitsongofficial/sinfonia-ui#293]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

cant bridge from sinfonia to osmos for the competition

### Describe the issue behavior

cant bridge from sinfonia to osmos for the competition

### BitSong Public Address

bitsong10w2mczmdjqxrycxeypjtwhe88k2zln4hglv5je

### Osmosis Public Address

osmo10w2mczmdjqxrycxeypjtwhe88k2zln4hvddvxy

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Did you follow the guide?

Can you please attach images or videos to help in debugging?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.

**Comment by ardiansajen** [comment]
[image: sinfonia always failed when bridge.png]

**Comment by DavideSegullo** [comment]
@ardiansajen Please add a screenshot, if you don't provide more info on the 12th of may (12:00 am UTC) the issue will be closed.
