### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by nayapurnomo** [bitsongofficial/sinfonia-ui#297]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You checked that the enhancement has not yet been reported (also through closed issues).

### Describe the current behavior

Simple UI,  I Like

### Explain the motivation

Simple UI,  I Like

### Provide a list of references

Simple UI,  I Like

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Mobile

### Are you using a ledger?

No

**Comment by Giorgionocera** [comment]
Thank you!
