### ISSUE TITLE
Page Enhancement 

### ISSUE THREAD

**Issue by ceejayzz** [bitsongofficial/sinfonia-ui#298]
I want to bless the Lord almighty for the privilege to make me experience this awesome and wonderful, yet, mind-blowing platform. 

I wanna talk about the use of colors first, I think some attractive colors would make the webpage more beautiful but given this present design, I guess the plan is to make it simple and complex-free as it is.

There is also a noticeable error on stage 3 on keplr confirmation. Though it seems the transaction is successful but a pop up comes from keplr that there has been an error in the transaction. Perhaps there should be serious more work on the nodes. 

Lastly, I would like to encourage the amiable members of this great community. Let's support this project because it will stand the test of time. and will definitely reach to the moon.  Regards

**Comment by Giorgionocera** [comment]
Thank you for your feedback. Can I please ask you to give us more information? 

Thank you!!
