### ISSUE TITLE
[Competition Bug]: Ui and notification bug

### ISSUE THREAD

**Issue by Roovys** [bitsongofficial/sinfonia-ui#299]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

First issue : {Transaction notification last forever}

 This sounds silly because I made the transaction fail on purpose.
 
 So, if you go to pools and unbind your assets, then click "Unbound all," you'll accept the transaction; however, if you click "Unbound all" again before the most recent transaction has completed, you'll get an error.
 
Even if the transaction has already completed and the unbounding has been done, the "Transaction Broadcasting" notification will not go away, but the error notification disappeared.

i will show you how to do it on this video.

Next issues

-

Second issues : ( Some part of the website didnt follow the website theme) 
Just a small UI bug i guess

so if you go to your tokens pools detail, you can clearly see the "Pool compositon" circles.
The circle is split in half, with the left side being black or white and the right side being pink (adjusting the web theme)
How to see the bug? It's a bit difficult to explain in words, but I'll try to make it understandable.

So, with dark mode on, go to https://sinfonia.pages.dev/pools and select ur desired pool, it can be any tokens you like, then change it to light mode. You can see the left circles color is white when dark mode is on, then when you change it to light mode, the left circles convert into black color, Everything appears to be normal here; the left circles are changing colors to make them easier to view on any website theme.

But, when u go to https://sinfonia.pages.dev/pools with light mode on, select ur desired pool, u can see the left circle turned into white, and when u switch it between dark/light theme, the cirlces just wont change the colour, its stays on white, u must go back to pool page with dark mode on, and select ur pool, u can switch any theme between dark/light, and the cirlce will follow the theme.

the bug is on light mode i guess

### Describe the issue behavior

Even if the transaction has already completed and the unbounding has been done, the "Transaction Broadcasting" notification will not go away, but the error notification disappeared.

https://user-images.githubusercontent.com/91830138/167581974-c376587a-5de2-45aa-9717-6b7638cecbfa.mp4

Move to next issues.

Second issues, as u can see on my video, the left circles wont change colour if you on light mode.

https://user-images.githubusercontent.com/91830138/167594047-c9ddfb46-7099-44a9-8e63-63b061a2eb2a.mp4

Edit 
12:07
Thursday, May 12, 2022
Coordinated Universal Time (UTC)

https://user-images.githubusercontent.com/91830138/168071077-bb1862a6-a90a-4a1b-8c4a-ba068cc67989.mp4

this happned to token analytics  section too, u can see clearly the left side circle wont change colour in any theme, you must go back and then change theme, then the circle will changed colour

### BitSong Public Address

bitsong1fzgx606mmmhv0qwwgp32u30j24vz0yv9l8fcg8

### Osmosis Public Address

osmo1fqgg5pvzma2znu9w5rhglshjwc2nlzn878q0c5

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 (Official Build) (64-bit) (cohort: Stable) 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
We answered you on #192.
