### ISSUE TITLE
[Competition bug]:

### ISSUE THREAD

**Issue by Captain9440** [bitsongofficial/sinfonia-ui#301]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Adam city pool is not working as expected 

### Describe the issue behavior

Failing to add liquidity in Adam clay pool.

I tried several times before I'm able to add liquidity into the pool.

### BitSong Public Address

bitsong1e52k6k43tu0l7n9c3g6q3eexkhvrntx9qvheva

### Osmosis Public Address

osmo1crwtnmjzmfpq2rd58q6an2fgjp65u8lvetj5c2

### Which browser are you using?

Google Chrome

### Which is your browser version?

Microsoft edge 101.0.1210.39

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Can you please add videos or images?

Thank you.

**Comment by Giorgionocera** [comment]
If no comment is released on the 11th of may (12:00 am UTC) the issue will be closed.
