### ISSUE TITLE
[Competition Bug]: Bugs Bond/Unbond From Liquidity

### ISSUE THREAD

**Issue by lanaibra** [bitsongofficial/sinfonia-ui#303]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

i have entered/tried this feature several times.. 
1. Enter the Pools menu 
2. Enter to start earning 
3. Bond tokens 
on number 3 this is my note.. as explained in the symphonic medium of the guild "There are 3 choices for participants for Bond Tokens" ie the problem of duration . Participants have the right to choose between 6 hours 12 hours and 1 day to bind participant token. "I tried my bond token with a duration of 1 day" but it's only been a few hours. and i tried it to unbond . (transaction successful) the conclusion is that on the bond token menu there are 3 choices between 6 hours, 12 hours and 1 day not working properly / broken / bugs

### Describe the issue behavior

.Participants have the right to choose between 6 hours 12 hours and 1 day to bind participant token. "I tried my bond token with a duration of 1 day" but it's only been a few hours. and i tried it to unbond . (transaction successful) the conclusion is that on the bond token menu there are 3 choices between 6 hours, 12 hours and 1 day not working properly / broken / bugs

### BitSong Public Address

bitsong1chqa2zk9hjsswnfc8hesh9etya94r69arluxyl

### Osmosis Public Address

osmo10xdfuy4rh5flspvtllefr5e56xkuaq8wj453xd

### Which browser are you using?

Google Chrome

### Which is your browser version?

0.10.3

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

0.10.3

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The unbonding time is related to the fact that starting from your unbending transaction, you will need to wait for respectively 6h, 12h, or 1d to get back your tokens.

As a consequence, this is definitely not a bug.
