### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Windboyz** [bitsongofficial/sinfonia-ui#304]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Dear sir
I just already unbound my bounded assets at Vibra and it successfull but when I want to put available token and the ammount is not appear. I have screenshot the error

### Describe the issue behavior

[
![BITSONG 2](https://user-images.githubusercontent.com/102676285/167628291-4be2489c-622d-4955-92b3-b02ec9b5def1.png)
![BITSONG](https://user-images.githubusercontent.com/102676285/167628309-2166cdd1-4d86-4ba1-85bd-9d3b43ce1d4f.png)
](url)

### BitSong Public Address

bitsong10ex84utq7s84jgyd46qhnker2x8knuynxa67px

### Osmosis Public Address

osmo1h0asx40fwrcrsvl64ak8uz0hxmseevlcurv7kr

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Your tokens are under an unbonding period. You have to wait for the bonding period (which is shown in your second screenshot) to use them again.

This is definitely not a bug.
