### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by amau15** [bitsongofficial/sinfonia-ui#310]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

![Screenshot_20220510_212330](https://user-images.githubusercontent.com/56421276/167653172-2a05513b-f7c7-4059-a019-eea2f3543c80.jpg)
vibra/BTSG pair liquidity is not working or transaction is not successful

### Describe the issue behavior

![Screenshot_20220510_212330](https://user-images.githubusercontent.com/56421276/167653447-d23a3672-9885-4a93-8fb4-87a522a7d517.jpg)

vibra/BTSG pair liquidity is not working or transaction is not successful

### BitSong Public Address

bitsong1k7a0r83d8ms79cmzqh6mdrmk0lwy8yqka5nuvr

### Osmosis Public Address

osmo1s2lqe7x8m5d3cdfq63cq580qldjadnxcewm7x0

### Which browser are you using?

Google Chrome

### Which is your browser version?

22.3.6

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
