### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Tokmbel** [bitsongofficial/sinfonia-ui#311]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

not see my token BTSG

### Describe the issue behavior

when i success tranfer my BTSG token to osmos and i will swap my BTSG i not see my balance, i'm must refresh browser to see and too long

### BitSong Public Address

bitsong1hls5y59dqmdaxvn4knvcw8faegk2lmprsnctqr

### Osmosis Public Address

osmo1zs48m9mnl6e9sfm7fl7k2yhejnq08sjwnfmadx

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by DavideSegullo** [comment]
Duplicated #96
