### ISSUE TITLE
[Competition Bug]: Error Add Liquidty

### ISSUE THREAD

**Issue by Tokmbel** [bitsongofficial/sinfonia-ui#312]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Error Add Liquidty

### Describe the issue behavior

when i will add liquidy  VIBRA/BTSG on single asset LP this failed and error

### BitSong Public Address

bitsong1hls5y59dqmdaxvn4knvcw8faegk2lmprsnctqr

### Osmosis Public Address

osmo1zs48m9mnl6e9sfm7fl7k2yhejnq08sjwnfmadx

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Tokmbel** [comment]
![Bitsong](https://user-images.githubusercontent.com/105298118/168813655-01974b7f-45f6-473a-be43-cbaba181b5f7.jpg)

the problem done when i'm refresh my browser

**Comment by Giorgionocera** [comment]
You are on a page that is different from the one in which you can add liquidity to the pool. We cannot understand what you are talking about.
