### ISSUE TITLE
[Competition Bug]: Chain Add Request Pop-Up Bug

### ISSUE THREAD

**Issue by Dee0622** [bitsongofficial/sinfonia-ui#313]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Hello. I connect Keplr on the platform. It connects well. But as I try to navigate with the features, multiple times the Keplr wallet is popping up showing "Chain Add Request" even though the bitsong wallet address is connected already on the platform. 

### Describe the issue behavior

This pop-up bug is showing when I go to another tab then return or when I refresh the page. Yes, it can be the case that I got disconnected but my bitsong address is showing on the page, therefore it's clearly a bug. This pop-up showed thrice as I was testing. 

![279267842_4975438642555504_2180951930415671548_n](https://user-images.githubusercontent.com/86071351/167663671-87a1a68e-b3b9-4100-9891-ce1c3e58f624.jpg)

### BitSong Public Address

bitsong1g76qrlyxhvpvra6hwgg8esqznev2g0dl3mnfpw

### Osmosis Public Address

osmo1e6jk0hfj0n9g5kjxkf6e3lg86xe2qjl2gacpqs

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by DavideSegullo** [comment]
It isn't related to sinfonia, not sure if it is a bug, but can only be related to Keplr wallet
