### ISSUE TITLE
[Competition Bug]: BTSG 'Amount Available' is Zero & Transfer Details is Missing

### ISSUE THREAD

**Issue by Dee0622** [bitsongofficial/sinfonia-ui#314]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

There are two bugs I found during transferring of asset (BTSG) from Bitsong Testnet to Osmosis Testnet.

Bug 1: After connecting my BitSong address, the BTSG amount is not showing to the page. There is a need to refresh the page for it to appear. 

Bug 2: Aside from the BTSG Amount Available Bug, there is also a bug where the details of Transfer is not visible. 

### Describe the issue behavior

No Available BTSG and even the 'Transfer details' are not showing even though my BitSong wallet has funds of it. I expected that it will auto-reflect since I already connected my wallet. After some quite time of refreshing the page, the Transfer details is complete along with the total amount of BTSG  and ready for a transaction.

Bug 1:
![279020955_721694045941662_2294914454878592767_n](https://user-images.githubusercontent.com/86071351/167666767-8c52ac61-2761-4168-8db0-7ad7f153e4ad.jpg)

Bug 2:
![279835932_3066615536981961_2042311484106353568_n](https://user-images.githubusercontent.com/86071351/167668172-59326af3-0244-4afd-a002-af3255f141ae.jpg)

### BitSong Public Address

bitsong1g76qrlyxhvpvra6hwgg8esqznev2g0dl3mnfpw

### Osmosis Public Address

osmo1e6jk0hfj0n9g5kjxkf6e3lg86xe2qjl2gacpqs

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

N/A

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Hello, can you provide us with a video of the issue? It is not possible to reproduce it.

Please add the content before 2nd June, otherwise, the issue will be closed.
