### ISSUE TITLE
not working for add liquid

### ISSUE THREAD

**Issue by hengky29** [bitsongofficial/sinfonia-ui#316]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I found a problem that I think is very troublesome,
For blackjack records and puro lobo, it's a problem because it can't be added to add liquidity, I have tried to increase/decrease gassfee but the result is still the same, I hope that when the mainnet comes out you can fix it.
because it will harm the user in wasting gas fee

for the others work well thanks for giving us a chance to try your project☺️

### Describe the issue behavior

problem in add liquidity which failed and spent gas fee

### BitSong Public Address

bitsong1sar7ayl7x99v0p302r0xphz7lw50qfmgdv6g6u

### Osmosis Public Address

cosmos1jhw3y2x7rgwt7gkld8ywlwm80ka2nkfds4fpnn

### Which browser are you using?

Google Chrome

### Which is your browser version?

yandex(alpha) 22.1.7.0

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This occurred due to the high volatility of the price and the nature of the testnet.

For this reason, it is definitely not a bug.
