### ISSUE TITLE
[Competition Bug]: bug report

### ISSUE THREAD

**Issue by ali270793** [bitsongofficial/sinfonia-ui#317]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I swapped BTSG TO CLAY

### Describe the issue behavior

I swapped BTSG TO CLAY The transaction was successful but it says it's still BROAD CASTING...

![Screenshot_20220510_182410](https://user-images.githubusercontent.com/59775102/167683574-280ff36d-7abb-4ac4-9f6e-ab92871f01a1.jpg)
![Screenshot_20220510_234848](https://user-images.githubusercontent.com/59775102/167683587-96c25dd8-36b0-4f92-a277-eaaccecb81dc.jpg)
![Screenshot_20220510_234202](https://user-images.githubusercontent.com/59775102/167683591-69bf12c9-09f1-4aca-bea9-058d986ebbc3.jpg)

### BitSong Public Address

bitsong14ly6mpcrrdf59209tl2vmv7g9aak498khp0a8d

### Osmosis Public Address

osmo1pmklrdm79r3azukuz35q2gpl3rzueq9dqtu4lv

### Which browser are you using?

Google Chrome

### Which is your browser version?

99.0.4844.66

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

6.6.5.7

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
