### ISSUE TITLE
[Competition Bug]: visual bug all fan token profile

### ISSUE THREAD

**Issue by raflinurrahim** [bitsongofficial/sinfonia-ui#318]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

when viewing the fantoken profile there is a visual bug (purple line)

### Describe the issue behavior

when opening the fantoken profile, this purple line makes the browser response slow (lagging)
![sinfonia testnet bug 1](https://user-images.githubusercontent.com/100784538/167700828-6473ec65-82dc-4ece-9d65-36e34f3e47dd.jpg)

### BitSong Public Address

bitsong1f5v25slw75tv9lmyrgyq44v00g2p54rfpvtm0m

### Osmosis Public Address

osmo1zx4x4tfmqy89sanl2u20x6dudfz94lh7cszzjl

### Which browser are you using?

Google Chrome

### Which is your browser version?

75.0.3770.90

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by raflinurrahim** [comment]
I think not error, just visual ui/ux bug, but make a browser lagging/slow
responsive

**Comment by Giorgionocera** [comment]
Can you add videos about it?

Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.
