### ISSUE TITLE
Fan token menu element

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#32]
In the Fan token PDP, the menu elements are capitalized. In the implementation they are uppercase.

Implementation:
![menu-text-capitalization](https://user-images.githubusercontent.com/13519292/159718156-6ea7fc26-e606-45b4-8481-39cb654c1ed3.jpg)

Design:
![menu-text-capitalization-design](https://user-images.githubusercontent.com/13519292/159718135-18a7e1e2-ecd0-4331-86ae-cf9edeee0a7c.jpg)

**Comment by EnricoBarbieri1997** [comment]
Fixed in a previous commit

**Comment by Giorgionocera** [comment]
Thank you!
