### ISSUE TITLE
[Competition Bug]: The 'View All' beside the Transaction history tab on the swap area

### ISSUE THREAD

**Issue by Promkeys1** [bitsongofficial/sinfonia-ui#321]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

1) I swapped between different assets more than 10 times
2) I added liquidity in two different pools

### Describe the issue behavior

1) My transaction history only showed me my recent two swap transactions after my 10 swaps and adding of liquidity
2) The 'View all' feature of the transaction history area brought an empty blank page of "no transactions found" for me on Osmosis Mint Scan.
![Bitsong Bug](https://user-images.githubusercontent.com/78166975/167723490-912f2a7c-dd85-409a-8fa9-9e302a8dd633.gif)
 

### BitSong Public Address

bitsong1ppkz9ywhejj6hr43fz5uvcfpf47w5zg5g4wuff

### Osmosis Public Address

osmo1v3ecf4ma2whf3w7t5wv8qzqt54kpl3mc9ruww8

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by DavideSegullo** [comment]
Hello, thank for your feedback.

It's not an issue, right now mintscan doesn't work on the testnet, but ofc it'll works on mainnet.

**Comment by Giorgionocera** [comment]
With respect to the history, you maybe had a clean of your cache. So you cannot see the swap anymore.
This issue is duplicated for #173.
