### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Zevanasth** [bitsongofficial/sinfonia-ui#324]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

when I was going to transfer from bitsong to osmosis, a few moments later an error occurred even though the wallet I used when I signed up for the testnet I had connected.

### Describe the issue behavior

error that occurs when I make a transfer from bitsong to osmos

### BitSong Public Address

bitsong1s4xu35rcpwr0l208umkdcarrwjkwjr0ng49rmp

### Osmosis Public Address

osmo1fatvguj5ustwdrrty54e0m39z5wg0cyvqcegj4

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Can you please add more information about the actions?
For example, adding a screenshot or a video.

Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.
