### ISSUE TITLE
[Bug]: the price not same

### ISSUE THREAD

**Issue by Eldhamana** [bitsongofficial/sinfonia-ui#326]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

my token BTSG price not same. its and its so weird 

### Describe the issue behavior

![Capture](https://user-images.githubusercontent.com/103091334/167759408-2959b499-67db-4154-a98f-9ef1bbbd2bc4.PNG)

my token price is not correct and very strange

### BitSong Public Address

0x93DB9956a56e49783A197A5e0c12B5D1354F6e06

### Osmosis Public Address

osmo1jefnk3sf7rd4fh0lal2sg0z9r52refmlj7t6ku

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

**Comment by Giorgionocera** [comment]
Hi, what do you mean by "my token BTSG price not same. its and its so weird"?

Moreover, this address "0x93DB9956a56e49783A197A5e0c12B5D1354F6e06" is not a bitsong address.

Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.
