### ISSUE TITLE
[Competition Bug]: Manage Liquidity Asset Amount Bug

### ISSUE THREAD

**Issue by Dee0622** [bitsongofficial/sinfonia-ui#327]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

As I was adding Liquidity, I encountered two scenarios which is bug.

Bug 1: Both two coin pairs (BTSG and CLAY) that I would like to add Liquidity is showing insufficient funds/zero funds.
Bug 2: There is a time, only one coin is bugged. The amount of BTSG says insufficient even though I already have swapped enough of it. Its asset pair which is CLAY does not have any issue and shows the exact amount. Just the BTSG amount is the bug. 

Both issues above is fixed through refreshing the page.

### Describe the issue behavior

Bug 1: Here we can see that both the coins are showing Insufficient funds for BTSG and zero for CLAY even though my BitSong wallet has enough funds of it.

![279425701_3238270763054848_7882533168957330076_n](https://user-images.githubusercontent.com/86071351/167762099-8b7524f0-14ae-4e3c-abd0-6ed214da24bb.jpg)

Bug 2: Here you can see the message showing "You don't have enough coins' in BTSG. Before refreshing:

![279410400_1608708382862974_301373952926242156_n](https://user-images.githubusercontent.com/86071351/167761017-f95aa8d6-0b63-483e-bf47-1e2131b1dad4.jpg)

But after refreshing the page, the BTSG are then updated with the actual amount of it. 
![279927579_764047904760860_4494941836584369204_n](https://user-images.githubusercontent.com/86071351/167761095-2813d8ce-4448-488c-97b2-7bfe29ea3854.jpg)

### BitSong Public Address

bitsong1g76qrlyxhvpvra6hwgg8esqznev2g0dl3mnfpw

### Osmosis Public Address

osmo1e6jk0hfj0n9g5kjxkf6e3lg86xe2qjl2gacpqs

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

N/A

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
On the first bug, you have to read the error: "Amount must be greater than zero". 
You are using "0" as a number, so you need to change that number.

For the second one, you can see that you have 345.564302, while you are trying to bond a value > 348. So, you do not have enough coins.

This is definitely not a bug.
