### ISSUE TITLE
[Competition Bug]: UI Display Bug: Swap & Assets Section

### ISSUE THREAD

**Issue by Dee0622** [bitsongofficial/sinfonia-ui#328]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

**ASSETS SECTION**
After successful transfer from BitSong Testnet to Osmosis, the amount was deducted on KEPLR wallet but on the interface (Assets Section) it does not reflect yet. 

**SWAP SECTION**
After successful swap of coins, message pop-up shows "Transaction successful" but the page does not refresh/reset. 

### Describe the issue behavior

**ASSETS SECTION**

BTSG amount is not updating after successful transfer. Needs to refresh the page to fix the issue.

![279662443_298976205764871_1821866877846448818_n](https://user-images.githubusercontent.com/86071351/167765127-ea33c354-f29a-43bf-8b2c-94a6e451ee01.jpg)

**SWAP SECTION**

In here we can see Successful Transaction in Swap, but after it, the details on the page is still there. It is commendable that it must be reset to avoid unintentional swapping again of the said pair. 

![277830308_332187072355565_3163125823299960604_n](https://user-images.githubusercontent.com/86071351/167765344-7787db97-8ab9-4f4b-af8a-4d8477aa578e.jpg)

**Suggestion**: Transaction hash may be added for every successful transaction for transparency.

### BitSong Public Address

bitsong1g76qrlyxhvpvra6hwgg8esqznev2g0dl3mnfpw

### Osmosis Public Address

osmo1e6jk0hfj0n9g5kjxkf6e3lg86xe2qjl2gacpqs

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

N/A

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Mr94t3z** [comment]
yeah, i had the same issue

**Comment by Validatrium** [comment]
got very same issue
screenshot attached
![bitsong interface bug](https://user-images.githubusercontent.com/88688112/167868533-7dde499d-f557-4cd0-af24-d39cb05cd29c.png)

**Comment by Giorgionocera** [comment]
No comments for 14 days. In my opinion, this issue can be closed.
