### ISSUE TITLE
[Competition Bug]: CORS Blocked

### ISSUE THREAD

**Issue by Cakpes1** [bitsongofficial/sinfonia-ui#330]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

from the console on chrome when testing the sinfonia protocol and i found strange behavior.

### Describe the issue behavior

<html>
<body>

Request | Status | Preflight Request (if problematic) | Header | Problem | Invalid Value (if available)
rum | blocked |   | Access-Control-Allow-Origin | Missing Header |  
rum | blocked |   | Access-Control-Allow-Origin | Missing Header |  
rum | blocked |   | Access-Control-Allow-Origin | Missing Header

<br class="Apple-interchange-newline">
</body>
</html>

A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request .
To fix this issue, ensure the response to the CORS request and/or the associated preflight request are not missing headers and use valid header values.

### BitSong Public Address

bitsong1mkqf58y9m32yjt738k4h8xcecvpwdlmpnrx2u3

### Osmosis Public Address

osmo1mkqf58y9m32yjt738k4h8xcecvpwdlmph38jgv

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by DavideSegullo** [comment]
It isn't a bug related to Sinfonia, actually doesn't create any trouble for the application, that's only related to cloudflare. But tnx for your feedback
