### ISSUE TITLE
[Enhancement]: Provide a button ("HALF") to pull half of the available selected token 

### ISSUE THREAD

**Issue by travazstake** [bitsongofficial/sinfonia-ui#335]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You checked that the enhancement has not yet been reported (also through closed issues).

### Describe the current behavior

The current state of the swap utility UI on Sinfonia allows selecting the maximum available amount of token when performing a swap. It would be optimal to have similar functionality to automatically select **half** of the tokens available when performing a swap with another token provided by the DEX.

### Explain the motivation

The main reason I believe it would be a good idea to add such functionality is that most of the swaps that are currently performed on the Sinfonia DEX have the purpose of providing full liquidity (with a 50% / 50% LP provision) to a pool. Such functionality would simplify the user experience even further by automatically splitting the tokens that should be provided to a specific pool. 

### Provide a list of references

The most relevant DEX that provides such functionality is: [Osmosis](https://app.osmosis.zone/)
<img width="618" alt="image" src="https://user-images.githubusercontent.com/100215982/167837515-ef8d0fae-d115-4577-8aa4-068163e77f57.png">

### Which browser are you using?

Brave

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

**Comment by giannnni** [comment]
Fixed as suggested. 
Redesigning the whole SWAP component, we added a small button above "max".

<img width="1006" alt="Schermata 2022-05-25 alle 14 34 23" src="https://user-images.githubusercontent.com/92384659/170263026-8f8f7077-ddd1-4684-b6c7-52d144cde487.png">
