### ISSUE TITLE
[Competition Bug]: report 

### ISSUE THREAD

**Issue by mankpa45** [bitsongofficial/sinfonia-ui#337]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

When I clicked on the price data by coingecko it takes me to coingecko website.
So when I search for all fans token and other tokens on the website it isn't bringing any information up.
Thanks

### Describe the issue behavior

When I clicked on the price data by coingecko it takes me to coingecko website.
So when I search for all fans token and other tokens on the website it isn't bringing any information up.
Thanks
![IMG-20220511-WA0129](https://user-images.githubusercontent.com/78081343/167902723-b30ea0a9-f247-48dd-b8c9-211fe3480d05.jpg)

### BitSong Public Address

bitsong1nnzfhetdc0m7vrrlpl94muy3pzw0etf24aceac

### Osmosis Public Address

osmo1uhl3dgssvrlrv4a96scq976sx3tg4psfjq6lyw

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This is a testnet. For this reason, you cannot find FanTokens on coingecko.

This is definitely not a bug.
