### ISSUE TITLE
[Competition Bug]: different balance display of $BTSG on SINFONIA protocol and KEPLR wallet

### ISSUE THREAD

**Issue by Cakpes1** [bitsongofficial/sinfonia-ui#340]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

as of i removed 1 of my liquidity pools (vibranium/BTSG pair) , i found my balance of BTSG on sinfonia is 1.575 BTSG., and i checked on KEPLR is still 999.9900 BTSG.

### Describe the issue behavior

i think there is mismatch on SINFONIA and KEPLR wallet, so they don't reflect each other balance, or maybe the network on OSMOSIS is slow, so it takes time to display the exact balance of my wallet after transaction.. its been 30 minutes since i wait the right balance on my KEPLR, but still the same.

### BitSong Public Address

bitsong1mkqf58y9m32yjt738k4h8xcecvpwdlmpnrx2u3

### Osmosis Public Address

osmo1mkqf58y9m32yjt738k4h8xcecvpwdlmph38jgv

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Cakpes1** [comment]
oh its there, i forgot if i approving $BTSG asset to osmo.. sory for my awareness

**Comment by Giorgionocera** [comment]
It is not a problem ;)
