### ISSUE TITLE
[Competition Bug]: Transfer BTSG , Swap , Pools etc 

### ISSUE THREAD

**Issue by FranzKafk4** [bitsongofficial/sinfonia-ui#342]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Hi Sir / Ma'am , my name is Ridwan Pamungkas, from Indonesia . Twitter username : @Franz_Kafk1
I've participate this event (Sinfonia Testnet) , and i have 26000 BTSG coin. the 1st day i try when i join the testnet , im so excited. I have 10k BTSG token. there's a trouble on claiming the token testnet before. Where we need to go to the website for paste our address then we will get the token tesnet , this website : https://testnet.sinfonia.zone/
and how do im solve the it ? if in this case counted as a bug , then count it please . If not then don't 😁 
So what i do for claming the token ? i try so much way for it , i do on other browser , i open the website with using VPN , turn on and off Plane mode. And thats all not even works. But i don't give up on it. So i decide to wait the error message until it dissapper , and try again (about 10 mins after error massage comming up) and guess what ? yes its working ! so thats how i solve the bugs at claiming token BTSG testnet. 
The second bugs is when i try to send the 10k BTSG token (Bitsong Network) to (Osmosis Network). i don't know why i cant send my BTSG token to Osmosis Network. i try max , can't , about 5 Times do same thing. And im thinking about that , im sure that we can't send all of our amount token. Should keep a bit on bitsong testnet , and yes thats it right. i solve the bug transfer with lefting a bit amount. I type 9999. 
Third bug , the swap problems. Sometimes we cant swap with LP under 1% , it probably fail. How to solve that ? Use 3% and all good , happy earning ;)
Fourth Bug , still about the swap but on different case. When i want to swap from BTSG token to CLAY token (Fan Token) the tabs always close by it self. This is my way to fix the bug on it : open the tabs about 3 tabs , or more. The we can swap the token even the 1st tabs is closed , its fine. Just open another tabs (tabs 2) and all good. 
And the last Bug , Fifty Bug. This is the part , i saw the percentage on total liquidty. And i say... OMG this is good , this is how to ezpz to earn money from Sinfonia if mainet already launch. And yes , im agreed with that. even at the 1st time i joining some pools(CLAY) i bit confuse about what to do , and after i watch around its not hard like what i see. the bug is the timing between bound and bounded is not same like what it says , im really sure i set alarm on it. Kinda delay 1 hours but all good , i've earned 26k BTSG like what i said on the top :) all right , thats it. Thats all what i want to say about Bug Competition. Thank you so much , Sir / Ma'am. Im so glad can join the great opportunity 💎 
![Screenshot_2022-05-12-19-35-12-667_com yandex browser alpha](https://user-images.githubusercontent.com/105082659/168086018-ce3d74bd-370f-469b-8286-be691a2b19db.jpg)

### Describe the issue behavior

I already answer on top ☝️

### BitSong Public Address

bitsong18860mh0wpee2qsdw7wd4pa9qj525l4r84tnn4f

### Osmosis Public Address

osmo1sxd09zrtudw2tuhn3ftcvt68rptsa48g48nx6v

### Which browser are you using?

Google Chrome

### Which is your browser version?

Browser Alpha 22.51.57

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
