### ISSUE TITLE
[Competition Bug]: lapses in decorum

### ISSUE THREAD

**Issue by Alien901** [bitsongofficial/sinfonia-ui#345]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Swap tokens

### Describe the issue behavior

when u done swapping, the amounts should disappear from the list, but it stays there, also kind of missing half button, and weird thing it says amount must be greater than Zero, Like we don't know that!???

https://user-images.githubusercontent.com/6206953/168235598-3f533899-0443-4d3a-bcb2-f66d70ea87ed.mp4

### BitSong Public Address

bitsong1xxj3fmymyj39zycxerur5p0laz55wxdxk9fqjw

### Osmosis Public Address

osmo135pzc6yh5usgskvn3neuqvzatjuk57zdgs6803

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.67 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

N/A

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #160
