### ISSUE TITLE
Competition bug for pool action

### ISSUE THREAD

**Issue by ibuWiwiet** [bitsongofficial/sinfonia-ui#346]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

as a person who uses android, i have a problem when i want to do pool, the application exits back and forth, and is not responsive, but this can be solved by changing to desktop mode, although it has to be done repeatedly, but desktop mode is more responsive and i can do pool

### Describe the issue behavior

This can be solved by changing to desktop mode, although it has to be done repeatedly, but desktop mode is more responsive and i can do pool

### BitSong Public Address

bitsong1uhyj3yq9gjsr6mdkfgwykdvrytwxezhnp6peq9

### Which browser are you using?

Google Chrome

### Which is your browser version?

93.0.

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The prerequisites list is clear. The bug must affect a run on the Chrome browser accessed by a Desktop computer, not by using desktop mode on a mobile phone.
