### ISSUE TITLE
[Competition Bug]: failed add liquidity with max amount

### ISSUE THREAD

**Issue by doni221** [bitsongofficial/sinfonia-ui#350]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

![sinfonia](https://user-images.githubusercontent.com/100908819/168454949-e941b15e-c3df-40d5-b563-f28968aa01bd.jpg)

I have done a swab on the CLAY/BTSG pair, and when I wanted to add liquidity with the maximum amount, my liquidity was rejected. however, for other pairs add liquidity works well. this is a bug I found in the CLAY/BTSG pair. I hope this bug can be fixed. thanks you, i enjoy this testnet

### Describe the issue behavior

The only problem I found was that my transaction was rejected/failed when I add liquidity CLAY/BTSG with the maximum amount

### BitSong Public Address

bitsong1tpcmdzkjeqq3u83h9zkd39j2uvx55tqw7lyueu

### Osmosis Public Address

osmo1cw0tdp0nvh8kq7asnkxl6upjuyfuhjp5s98yx2

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.67

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This occurred due to the high volatility of the price. This is not a bug, because, you got exactly the correct error.

For this reason, it is definitely not a bug.
