### ISSUE TITLE
[Bug]: Transaction failed

### ISSUE THREAD

**Issue by Cryptograsi** [bitsongofficial/sinfonia-ui#352]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I traded BTSG coin for fan tokens, no problem at this stage. but I had problems twice while adding liquidity in the pool tab. the first was in the BJKS token and the second was in the Fasano token. After clicking the Add liquidity tab on both, I clicked the max option in the fan token section. BTSG amount automatically appeared below. I confirmed the transactions in the kplr wallet, but it gave a transaction failed warning. I did both the error-generating operations for the second time, but this time it did not give an error. Although I did both operations in the same way, it gave an error in the first one, and it did not give an error in the second one.
![sinfonia bug 1](https://user-images.githubusercontent.com/101165594/168485387-163d5a3a-78fc-4476-83ef-3476413fbe6b.png)
![sinfonia bug 2](https://user-images.githubusercontent.com/101165594/168485391-116c0908-cf5d-4b23-8943-7d9f320a1bc9.png)

### Describe the issue behavior

I honestly couldn't understand where the problem came from. The error was fixed in the second operations that I had already done in the same way. In the error report displayed on the screen, it gave a warning of insufficient funds; but my resources were not sufficient. My internet connection weakened the moment I did the operation and this error occurred.

### BitSong Public Address

bitsong1ha2ut4j4nj4u20ma3alj3mxen6pgpxrfdfgxd2

### Osmosis Public Address

osmo1ha2ut4j4nj4u20ma3alj3mxen6pgpxrffmf7eh

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.67

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

**Comment by Giorgionocera** [comment]
This occurred due to the high volatility of the price. This is not a bug, because, you got exactly the correct error.

For this reason, it is definitely not a bug.
