### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Raxky** [bitsongofficial/sinfonia-ui#353]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I Dont know this is bug or NOT, But i have 1 issue. Please change type data to INTEGER in the textbox !

### Describe the issue behavior

I can typing Symbol in the value of my coin for swapping. ex: !@$%^&*() 

### BitSong Public Address

bitsong14th2ap4w0d30gdpm6awfzha0lmh70nrjathh4g

### Osmosis Public Address

osmo19ufr7xwcgukf5h8qlxwsa88hsx7w4sctjmny9u

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

Yes

### Which is your ledger version?

0.10.3

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #160.
