### ISSUE TITLE
[Competition Bug]: transaction swap ,fool etc

### ISSUE THREAD

**Issue by Martina66952** [bitsongofficial/sinfonia-ui#354]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

 hello my name martina my twitter @Martina66952 came from Indonesia.   
)) trade BTSG Vibra coin for swap the coin , but when i was about to swap and i pressed the swap button suddenly a notification of a failed transaction appeared even though i had not pressed approve and it really bothered me in the transaction,, after that i tried in fool symphonia when i was about to transfer liquidity clay coin and vibration it reappeared there transaction notification failed when i will approve..
![bitsong](https://user-images.githubusercontent.com/105481820/168577208-10b1a20f-2f32-4a8c-ae92-dbf40ee742cd.png)
![bitsong6](https://user-images.githubusercontent.com/105481820/168577456-c425fa5b-8b73-48f2-828b-fad0adc4ecea.png)
![bitsong4](https://user-images.githubusercontent.com/105481820/168577527-02aa22df-e16d-47d3-9e21-91b35326bfb1.png)

### Describe the issue behavior

I don't understand where the error came from when I was making a transaction, but the error kept repeating itself several times during the transaction.

### BitSong Public Address

bitsong1pxjrjunjnq4ltzzpfersshjmnxr3lh8e045wu3

### Osmosis Public Address

cosmos1pxjrjunjnq4ltzzpfersshjmnxr3lh8eruxx77

### Which browser are you using?

Google Chrome

### Which is your browser version?

versin 101 .0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

no

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Can you please add more information about the actions?
For example, adding a video?

Please leave a comment before the 18th of May (UTC). If there is no new comment, this issue will be closed.
