### ISSUE TITLE
Amount to transfer

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#356]
On the assets page, the "amount to transfer" label becomes **red** when you overcome a particular percentage. This behavior generates doubt in many people. We need to adjust it.
@giannnni can you help us?

@DavideSegullo moreover we need to create this behavior only when you are moving tokens from the native chain to another one.

**Comment by giannnni** [comment]
We could avoid to show any red label (as error message) because it's difficult to understand for users why moving more than 20% could be a trouble, so in my opinion there isn't any real or perceived error to show.

**Comment by Giorgionocera** [comment]
Thank you!
