### ISSUE TITLE
[Competition Transaction Swap and Pool exc.

### ISSUE THREAD

**Issue by Martina66952** [bitsongofficial/sinfonia-ui#357]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

hello my name Martina came from indonesia . I I followed this airdrop and wanted to report an error on a bug that I was experiencing, when I was doing a swap transaction and typing the swap button suddenly a failed transaction notification appeared even though I had not approved it, and when I made a transaction in the pool it repeated several times and it really annoys me in transactions..thank you
![bitsong](https://user-images.githubusercontent.com/105481820/168681575-401308cd-3193-4b13-bd36-8e1509a05379.png)
![bitsong6](https://user-images.githubusercontent.com/105481820/168681689-466ad5dc-2bab-46bf-9457-9b78bf7a3023.png)

### Describe the issue behavior

I don't know where the error originally came from, but the error appeared repeatedly and annoys me in my transactions.

### BitSong Public Address

bitsong1pxjrjunjnq4ltzzpfersshjmnxr3lh8e045wu3

### Osmosis Public Address

cosmos1pxjrjunjnq4ltzzpfersshjmnxr3lh8eruxx77

### Which browser are you using?

Google Chrome

### Which is your browser version?

version 101.0.4951.67 (official build)(64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Which is your ledger version?

no

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #354
