### ISSUE TITLE
Playground menu doesn't exist [Competition Bug]: 

### ISSUE THREAD

**Issue by ngulitipis2** [bitsongofficial/sinfonia-ui#358]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

https://testnet.sinfonia.zone/playground if i click this link, the link doesnt exist sir. 
![image](https://user-images.githubusercontent.com/100993011/168739687-90f4343e-5b5a-408b-872e-4b1d63f1bd96.png)

### Describe the issue behavior

I've tried testnet since the beginning but until now the playground table never appears so I don't have a faucet balance.

### BitSong Public Address

bitsong10hmu87jy2a7p9xz9f6qp7xp882gypg2sw85v25

### Osmosis Public Address

osmo1clze5qlqkl73jerzyh9h4k8e6d6n04qdfsgezp

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
The playground page will be available with other information in the next few days. But it is not needed to interact with Sinfonia. Please, read the guide https://docs.bitsong.io/useful-guides/sinfonia-users-guide

This is definitely not a bug.
