### ISSUE TITLE
add a half button to drag half of each asset you want to select

### ISSUE THREAD

**Issue by Silvanasilvia** [bitsongofficial/sinfonia-ui#359]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

found in Sinfonia's current swap utility UI status allows selecting the maximum number of tokens available when swapping. It would be optimal to have a similar function to automatically select half of the available tokens when swapping with other tokens provided by WEB DEX .

### Describe the issue behavior

The main reason I believe it would be a good idea to add such functionality is that most of the swaps currently being done on Sinfonia DEX aim to provide full liquidity (with 50%/50% LP terms) to the pool. Such functionality will simplify the user experience even further by automatically dividing the tokens that should be reserved into specific pools and being able to grow even further .

### BitSong Public Address

bitsong14sujuy8peg3qy7exnyd7sx5zfjve35mzn9jl48

### Osmosis Public Address

osmo1d33ggeekmay2ehszzxv9ldr2wm3szq752xpftv

### Which browser are you using?

Google Chrome

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Thank you for your suggestion. But this is not a bug. You should fill in the template to propose a new enhancement.
