### ISSUE TITLE
[Competition Bug]: pop up window when doing swap with big step size 

### ISSUE THREAD

**Issue by Uladzik14** [bitsongofficial/sinfonia-ui#363]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

i went to swap page, chose btsg token and clay token, then i entered the amount of btsg - 170.44444444444 and pressed swap button

### Describe the issue behavior

I can't do swap when the step size is too big (170.444444444444 etc).

it doesn't even pop up a "transaction failed" message
![7983c1f6-1b20-4172-8d92-5de3e3835ec5](https://user-images.githubusercontent.com/105236630/169166865-850d3529-5fd7-451b-80f9-73c612562bfe.png)

### BitSong Public Address

bitsong1w60q3k507d9phcs7qqezt88w3ux5pzrlajhyd2

### Osmosis Public Address

osmo1j64uaqlm7v6pmr003p944d9tax08ke7sru8gmc

### Which browser are you using?

Google Chrome

### Which is your browser version?

101.0.4951.54 

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Duplicated of #160
