### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by 0xrzl** [bitsongofficial/sinfonia-ui#364]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

I tried to transfer $Bitsong to Osmosis to be able to join pools. But after the transfer was successful and I entered the Swap menu, the balance $BTSG not updated and had to refresh halam first

https://user-images.githubusercontent.com/105856258/169275070-093aed6a-42ae-4a1e-893b-cb5a3a0c3765.mp4

### Describe the issue behavior

Hello Bitsong Developer

Thank you for giving me the opportunity to try the testnet. I have one major concern where after I send Bitsong > Osmosis, the balance of $BTSG is not automatically updated (must refresh the page first)

But I am confident in the developer's ability to resolve this bug immediately. Thanks

### BitSong Public Address

bitsong1vhl79ynpfk3u8vj867v9v0x7v0madmtutjns6r

### Osmosis Public Address

osmo1pev6yhtx3983dks7kqfnugjp79qgvy0yqy0kra

### Which browser are you using?

Google Chrome

### Which is your browser version?

Version 101.0.4951.67 (Official Build) (64-bit)

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
Hello, thank you for this report. It is related to this issue #96
