### ISSUE TITLE
Improve Table Layout

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/sinfonia-ui#366]
There are some spacing issues with the current UI implementation:
![image](https://user-images.githubusercontent.com/17269969/169824693-e9a590f7-4168-4bbb-b614-033b1ccf6c27.png)

We should change it to respect Figma's design:
![image](https://user-images.githubusercontent.com/17269969/169825112-5c6c463e-5ab5-418b-ae6a-34b71b7041c2.png)

**Comment by giannnni** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/92384659/170277891-8c8a9288-3140-4d32-9b0f-c2502d41e776.png)

**Comment by Giorgionocera** [comment]
Thank you!
