### ISSUE TITLE
Improve Pools Layout

### ISSUE THREAD

**Issue by DavideSegullo** [bitsongofficial/sinfonia-ui#368]
We can improve pools layout by adding a layout switch button from cards rendering to table rendering, so we can provide more tools for search and sorting.

Maybe we can use the following table:
![image](https://user-images.githubusercontent.com/17269969/169827724-49bef9a3-2844-4f44-992d-efdd5e2d57d4.png)

Some references:
1. Astroport

**Comment by giannnni** [comment]
![image](https://user-images.githubusercontent.com/92384659/170262306-1ef6e0dd-ec2a-4ced-a854-24ad38a4a74e.png)

**Comment by DavideSegullo** [comment]
Duplicated of #388
