### ISSUE TITLE
[Competition Bug]: 

### ISSUE THREAD

**Issue by Cixuci** [bitsongofficial/sinfonia-ui#374]
### Prerequisites

- [X] You confirm that your bug is available through the Chrome browser accessed by a Desktop computer.
- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Sinfonia.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

when I transfer from Bitsong to Osm and vice versa I experience delays and when I swap also sometimes experience delays.

### Describe the issue behavior

when transfer and swap experience a very annoying delay.

### BitSong Public Address

bitsong1y9su37xsu40fck4jvr2fjh4nvqmelfc295cjkw

### Osmosis Public Address

osmo1u34jhu3r427xm4am4yqne2ax86fnaelczyucey

### Which browser are you using?

Google Chrome

### Which is your browser version?

10

### Which kind of device are you using?

Desktop

### Are you using a ledger?

No

### Agree the Competition Rules

- [X] You agree the competition rules

**Comment by Giorgionocera** [comment]
This is definitely not a bug.
