### ISSUE TITLE
Listing of gamm/pool

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#381]
At the moment, gamm/pool tokens are not listed on the assets page.
In this way, they do not appear in the total values on the top cards.
<img width="1680" alt="Schermata 2022-07-13 alle 10 17 40" src="https://user-images.githubusercontent.com/13519292/178685524-7051997f-c8b6-49ad-b7c7-1950e755eb35.png">

I think we could add these tokens (gamm/pool tokens) in a new table below the actual FanToken table, where we only list those tokens. 
@giannnni what do you think about this idea? 
Can you help us by realizing a design to solve this issue?

**Comment by Giorgionocera** [comment]
Thank you, @DavideSegullo we can move it in development.

**Comment by Giorgionocera** [comment]
@giannnni and @DavideSegullo why do we put the "GAMM Pool" table before the Tokens one?

What about swapping them (as we talked about at the beginning, with the Tokens table on top)?

**Comment by Giorgionocera** [comment]
Moreover, @DavideSegullo there is a bug in the context menu. It takes the wrong table for actions.

**Comment by DavideSegullo** [comment]
Actually I like it on top of the page, because I can see what I can bond inside the pools

**Comment by Giorgionocera** [comment]
Thank you!
