### ISSUE TITLE
Feedback on epoch time

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#384]
When the platform reaches the epoch time, the whole platform slows down in the requests.
For this reason, it could be helpful to show feedback to the user that shows that "things can be delayed".
We can think to add a tooltip near the epoch time countdown, or show a popup to every user on each page they're exactly at 00:00 of the epoch time.

@giannnni what do you think about it?

**Comment by giannnni** [comment]
To improve user experience while sinfonia reaching epoch times we could add a short text below the countdown when it reaches the end of the epoch, just to inform user that the platform is distributing rewards so they've to wait few minutes to receive those.


My suggestion here:
<img width="432" alt="Schermata 2022-07-13 alle 15 27 29" src="https://user-images.githubusercontent.com/92384659/178744919-3064db1c-1518-47e5-994d-3d50d3a33e6f.png">

**Comment by Giorgionocera** [comment]
@giannnni do you think it could be enough to show the message only on this page?

**Comment by giannnni** [comment]
Nice point, we could use a toast notification to remember users that could be some delays in Tx and generally using the platform when we're rewarding pool stakers.

Here an example:
<img width="383" alt="Schermata 2022-07-22 alle 16 30 26" src="https://user-images.githubusercontent.com/92384659/180461286-7a1a9986-8826-45f8-b96c-0bd15ca4ed21.png">

**Comment by Giorgionocera** [comment]
So it will be on top of the website.
I think it is a better solution. Thank you!
@DavideSegullo can we implement this new feature, please?

**Comment by DavideSegullo** [comment]
As we discussed with @giannnni, I wrote the code for the first suggestion

**Comment by Giorgionocera** [comment]
Thank you!
