### ISSUE TITLE
Improve the Transactions and FanTokens list

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#386]
On the swap page, on the right, we have two different tables containing data. They are messy and the spacing inside is very incorrect. We should review such a component to provide a better user experience.

![listing](https://user-images.githubusercontent.com/13519292/178730557-851c2fc6-56df-4d90-a241-22f11d79db72.jpg)

**Comment by giannnni** [comment]
Totally agree. In addition to that we could provide better informations than now, switching FanToken list with a Balance preview, fixing margins and components.

Example provided below:
<img width="601" alt="Schermata 2022-07-13 alle 14 34 55" src="https://user-images.githubusercontent.com/92384659/178734729-0856004c-7c10-438b-9fca-97f3433b480c.png">

**Comment by Giorgionocera** [comment]
I think it is a nice solution. Thank you!

Let's see what @angelorc thinks about it.

**Comment by Giorgionocera** [comment]
As per the meeting with @angelorc , we need to remove the extra info on the swap page.
- [ ] remove the transactions and balance elements.
@giannnni we are in your hands 😏

**Comment by giannnni** [comment]
Hands of Time, little present. https://www.youtube.com/watch?v=KDmtOW8hd54

![image](https://user-images.githubusercontent.com/92384659/180241553-7d4a8342-24f3-47cc-a110-4460d1d483c1.png)

**Comment by Giorgionocera** [comment]
Do you provided also the mobile and tablet versions for this design implementation? 😄

**Comment by giannnni** [comment]
Mobile version: 
![Uploading image.png…]()

Tablet Version

**Comment by Giorgionocera** [comment]
Thank you @giannnni! 
@DavideSegullo we can implement it 😄

**Comment by Giorgionocera** [comment]
Thank you @DavideSegullo!!
Now the next step is to work on #385 (redesign of the swap component, token selector included).
