### ISSUE TITLE
Add breadcrumb

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#387]
At the moment, once a user reaches a specific pool (let me say Pool 751 a.k.a. CLAY/BTSG), on the menu, the only selected voice is the pool one.
We could try to show more information to the user, in order to give more specifications to the current position.

We could for example use a breadcrumb. What do you think about it, @giannnni ?

**Comment by giannnni** [comment]
Yes, I figured this component just on top of the page, near logo.

Look at the example below:
<img width="1014" alt="Schermata 2022-07-17 alle 16 36 37" src="https://user-images.githubusercontent.com/92384659/179403400-e2d301d8-e27f-4a5d-a58e-a452b736bd5c.png">

**Comment by Giorgionocera** [comment]
I think it is a very nice solution. Thank you!!
@DavideSegullo let's move it into development.

**Comment by Giorgionocera** [comment]
I dislike the change on the placeholder in the breadcrumb... Could we fix that?
I prefer to see directly the final data not a placeholder that after a while will change.

**Comment by Giorgionocera** [comment]
Now it is veeeeeery good! Thank you, man! 😄
