### ISSUE TITLE
List visualization for pools

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#388]
At the moment, we show the pools as cards. It could be useful to also provide a list visualization.
![Schermata 2022-07-13 alle 16 34 37](https://user-images.githubusercontent.com/13519292/178759952-52804eb2-78f9-4943-a73e-253c3c43f2a4.png)

An example (reference) for the pool visualization as a list is provided by [astroport](https://app.astroport.fi/pools).
![Schermata 2022-07-13 alle 16 34 57](https://user-images.githubusercontent.com/13519292/178760050-016ae36e-1a89-4ddc-879b-7f5c09f3b81e.png)

It could be good to provide two visualizations and not only one.
What do you propose @giannnni ?

**Comment by angelorc** [comment]
I like it

**Comment by Giorgionocera** [comment]
Thank you @giannnni !
@DavideSegullo we can move this to the development!

**Comment by DavideSegullo** [comment]
Yes, @giulioaiello we need some text for the subtitle under "All Pools", do you have any suggestions?

**Comment by Giorgionocera** [comment]
@giannnni and @DavideSegullo, I have a question:
Why do we use the list/grid visualization only for all pools and not for my pools?

**Comment by DavideSegullo** [comment]
I thought the same thing yesterday, but I think only the "All Pool" section was chosen because it also contains the "My Pools" section

**Comment by giulioaiello** [comment]
hi guys, i suggest to explain what you can do on this page. 

"On this page you can become a Liquidity Provider participating on the Sinfonia Pools. Bond your tokens to provide security to the network and earn rewards"

**Comment by Giorgionocera** [comment]
> 

Okay, but I need @giannnni is aware of the current visualization. Can you give us feedback? 😄

**Comment by giannnni** [comment]
I'm agree. Let's go @DavideSegullo!

**Comment by Giorgionocera** [comment]
Thank you all!
