### ISSUE TITLE
Total market cap

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#390]
In the FanTokens page list, it could be useful to add the total market cap as the total of the FanTokens single market caps.
This could help the user to understand the amount of circulating money.

@giannnni which solution do you propose?

**Comment by giannnni** [comment]
We could replicate the Balance Page layout with 4 boxes with highlighted KPI like Market Cap, Bonded Value, #Tokens.

An example provided here: ![image](https://user-images.githubusercontent.com/92384659/178970903-49baffc3-4d88-4f5d-a442-67fbcd028122.png)

**Comment by Giorgionocera** [comment]
As from the recent discussion, CoinMarketCap presents a set of features that can be useful also on Sinfonia.

Some examples: 
- [ ] the expression of the global market cap, in Box 1;
- [ ] the usage of filters, in Box 2 (in our case they could be artists, labels, etc. and, for music it could be the music style);
- [ ] the usage of an out-of-the-box grid.

![all_suggestions_boxes](https://user-images.githubusercontent.com/13519292/178991729-5ec5d4c8-ffc1-4d1b-b0bd-223b9358f08c.jpg) 

@giannnni what about following these suggestions?

**Comment by giannnni** [comment]
As discussed few minutes ago, you can see two different solutions for this rework here follow: 

• proposal 1: 
![image](https://user-images.githubusercontent.com/92384659/178994266-976a8fab-795a-45a2-9fcd-c4b36b7d8390.png)
• proposal 2: 
![image](https://user-images.githubusercontent.com/92384659/178994322-f45b9d19-92e6-4d0f-a09b-29961bde8905.png)

**Comment by Giorgionocera** [comment]
Let's wait for feedback from @angelorc.

**Comment by giannnni** [comment]
DEX Page - Summer Edition 
![image](https://user-images.githubusercontent.com/92384659/180242400-8e66511f-b718-4191-ac49-94516081f00c.png)

**Comment by Giorgionocera** [comment]
I think we really hit the nail on the head 😍 .
@DavideSegullo let's move it in development man!

**Comment by Giorgionocera** [comment]
I really like this implementation!!! Thank you @DavideSegullo.

Maybe we only need to improve the search bar animation on click and start developing the filter functionality.

**Comment by DavideSegullo** [comment]
Ye we can improve it, do we have some references? or any feedback about that?

**Comment by Giorgionocera** [comment]
That one is perfect, thank you, man!

We need to align the right text "The total market cap is [...]".

Please, could you do that?

**Comment by Giorgionocera** [comment]
Thank you!
