### ISSUE TITLE
Missing pools or FanToken

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#395]
At the moment, if a user tries to reach a pool page with a not existing pool ID (e.g., ID 1 => https://app.sinfonia.zone/pools/1), the result is a blank page. The same happens with the FanToken ID (e.g., https://app.sinfonia.zone/fantokens/ft2D8E7041556CE93E1EFD66C07C45D551A6AAAE01).
![Schermata 2022-07-14 alle 09 39 20](https://user-images.githubusercontent.com/13519292/178928516-6cfd40f2-03f4-4703-ac4f-fefe29005308.png)

This behavior should change and we can manage it in different ways:
- Simplest one is to redirect the user to the pools (or FanTokens) list page. This behavior is used also by Osmosis.
- Another solution is to create a "404 Not Found" page.

@giannnni what do you suggest?

**Comment by giannnni** [comment]
Not choosing between your two options, I made a simple 404 error page.

![image](https://user-images.githubusercontent.com/92384659/178959543-240c9521-4d3d-47cd-ba21-975cf13efa59.png)

**Comment by Giorgionocera** [comment]
I really like this page!! Thank you @giannnni !
@DavideSegullo let's move it in development ;)

**Comment by giulioaiello** [comment]
copy suggestion: 

1- Lost and insecure,
Where were you? Where were you?

The Fray 

2- Find me, I'm under your spell
Find me, I'll dig your well

Bob Dylan 

3- Lost, I was lost, I was lost 'til you loved me 

Maroon5

4- No woman no cry 

Bob Marley 

5- There's no one around,
There's no one around,
There's no one around,
There's no one around,

Chase & Status

6- You're the only one that I want
But we're not working (no)
Yeah, I told you from the start
I'm not perfect (oh)

Tate McRae, Khalid

**Comment by Giorgionocera** [comment]
Thank you @giulioaiello! 💪 I like 3 and 7 as a text for the page.

**Comment by giulioaiello** [comment]
my favs are 1 - 3 - 5 - 6 - 7

**Comment by Giorgionocera** [comment]
The content on the page is not center-aligned.

Design:
![telegram-cloud-photo-size-4-5967707138119809567-y](https://user-images.githubusercontent.com/13519292/180420673-d4774dd8-f9b9-44c1-a2cc-cdd2b218ab30.jpg)

Implementation:
![telegram-cloud-photo-size-4-5967707138119809568-y](https://user-images.githubusercontent.com/13519292/180420731-72623d92-cede-4786-b766-e8bf4fb8089c.jpg)

I understand it is linked to a matter of grid system. But @giannnni and @DavideSegullo , can we find a solution? 😃

**Comment by Giorgionocera** [comment]
Thank you 😄
