### ISSUE TITLE
Bug: Error when claiming airdrop with ledger

### ISSUE THREAD

**Issue by ctrl-Felix** [bitsongofficial/sinfonia-ui#397]
Users in the Discord reported that it's not possible to claim the airdrop on sinfonia with a ledger. Following error appears:
![grafik](https://user-images.githubusercontent.com/62290842/178999477-50e56170-28e9-46c2-8057-fc59f155832f.png)

**Comment by Giorgionocera** [comment]
It is a duplicate for #382.
Thank you.
