### ISSUE TITLE
Asset page tokens table

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#398]
On the assets page, the token table contains a set of information that could be rethought. In such a scenario, it could be better to better understand the information architecture behind the objects and try to figure out a new setup.

**Comment by giannnni** [comment]
My proposal is a set of column for:

· Preferred Icon
· Token Img
· Token Symbol
· Token Name
· Chain
· Price
· Available
· Quantity
· Move Icon
· Accordion Arrow Icon

Let me know if you're agree.

**Comment by Giorgionocera** [comment]
I think it is complete. Can you try to transform this architecture into a design now? 😜

**Comment by giannnni** [comment]
Oh you, little fox

<img width="909" alt="Schermata 2022-07-21 alle 16 32 54" src="https://user-images.githubusercontent.com/92384659/180240260-95143a27-c51f-4694-9d9b-1e4d110a73ce.png">

**Comment by Giorgionocera** [comment]
Thank you @DavideSegullo and @giannnni <3.

@DavideSegullo we need to fix some points:
- [ ] fix the order for Osmosis and BitSong chain in the corresponding column;
- [ ] add the corresponding icon in each row.

**Comment by Giorgionocera** [comment]
Thank you 😄
