### ISSUE TITLE
Reintegration of the Playground

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#401]
While testing the Sinfonia platform few months ago, we created a section where users could play with artists/ platform activities to gain fantokens as airdrops. This section was named Playground.
In order to preserve the perception by our users of this complex environment, showing users that Sinfonia in not only a DEX, I suggest to reintegrate this page even without any activity at this moment.

We could put a placeholder to advice users to pay attention on our next moves inside Sinfonia, putting some hype on our following feature.

What do you think @Giorgionocera

**Comment by Giorgionocera** [comment]
Thank you @giannnni !
@giulioaiello can you please provide us with the texts for this page?

**Comment by DavideSegullo** [comment]
I have integrated the page, let's wait @giulioaiello for the texts, thank you

**Comment by giulioaiello** [comment]
ok so guys, in memory of the europa football cup, i suggest to use to famous song associated to the "cup" prize. 
what do you think? 

🎶 I'm coming home
I'm coming home 🎙

Dirty money ft. Skylar Grey 

"Nothing to do here at moment, more prizes coming soon!
Stay updated "

**Comment by DavideSegullo** [comment]
@giulioaiello What title do you suggest?

**Comment by Giorgionocera** [comment]
Perfect! Thank you!
