### ISSUE TITLE
Missing placeholder

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#402]
The placeholder for an empty history of transactions is missing at the moment.
We need to add it.

![missing-placeholder](https://user-images.githubusercontent.com/13519292/179617637-5410e3c6-6724-487e-b8a7-e96f51d097bf.jpg)

**Comment by DavideSegullo** [comment]
@Giorgionocera  I think we can close this issue, as this section is being removed #386

**Comment by Giorgionocera** [comment]
You are right! 💪  
Bye-bye issue!
