### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#405]
As per the meeting with @angelorc, we are removing the transactions list from the swap page (as said in issue #386).
In this sense, we can think of a new approach with a notification system for the user, where we can also show the transactions as notifications.

**Comment by giannnni** [comment]
As discussed in previous meetings, I suggest a simple notification icon on the right top of the page, opening a dropdown when clicked. The icon will change when a transaction is processing, showing the same spinner we use in toast notification until the Tx is validated, allowing user to monitor status of Txs from every page without opening the component.

<img width="832" alt="Schermata 2022-07-22 alle 15 39 37" src="https://user-images.githubusercontent.com/92384659/180451179-b07b46a7-891a-4e71-998b-c4fec4c987c5.png">

**Comment by Giorgionocera** [comment]
It is very nice 😍 ! 
@giannnni, do we also have the tablet and mobile design for the component?

Moreover, @DavideSegullo  we can make the text clickable for referring to the tx on mintscan!

**Comment by Giorgionocera** [comment]
@DavideSegullo, maybe it could be useful to also give a look at issue #96.

**Comment by DavideSegullo** [comment]
Ok, I'll remove the old notifications system, the one that appears at the top center, do you agree with me @Giorgionocera @giannnni ?

**Comment by DavideSegullo** [comment]
I removed the old notification system, I chose to keep the success and error messages anyway, what do you think? @Giorgionocera @giannnni

**Comment by Giorgionocera** [comment]
I'd like to listen to @giannnni feedback, even if I like the solution you proposed.

**Comment by giannnni** [comment]
Yes I like it @DavideSegullo and as I said in our last call you could go to the bar and ask for an Ham&Cheese Toast Notification if missing.

**Comment by Giorgionocera** [comment]
At the moment only the swap actions are tracked as notifications. 
IMHO we should trace all other actions: 
- [ ] join pool x;
- [ ] remove from pool x; 
- [ ] lock x tokens;
- [ ] unlock x tokens;
- [ ] transfer from chain A to chain B;
- [ ] claim an airdrop.

@giannnni, @DavideSegullo, and @giulioaiello please, give me feedback ASAP (in case you agree, please, @giulioaiello you need to provide us with the corresponding texts).

**Comment by DavideSegullo** [comment]
@Giorgionocera  Just some notes, with "lock x tokens" and "unlock x tokens" do you mean GAMM?

We can also add the airdrop ID or name for "Claim an airdrop" and change it likes "you redeemed foo airdrop"

**Comment by Giorgionocera** [comment]
> @Giorgionocera Just some notes, with "lock x tokens" and "unlock x tokens" do you mean GAMM?
We can also add the airdrop ID or name for "Claim an airdrop" and change it likes "you redeemed foo airdrop"

You got it!

**Comment by Giorgionocera** [comment]
Perfect! Thank you!
