### ISSUE TITLE
Total FanToken liquidity

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#407]
In the Pools page list, it could be useful to add the "total FanToken liquidity" as the total of the FanTokens pools liquidity.

@giannnni we need a solution identical to this #390.
Could you help us?

**Comment by giannnni** [comment]
Yes, you could find a similar proposal here: 
![image](https://user-images.githubusercontent.com/92384659/180985907-dc72f57b-dfaf-434c-b664-de139a86e50b.png)

Maybe this approach will trigger a little fix on #390 issue moving market cap info near the page title: 
![image](https://user-images.githubusercontent.com/92384659/180986227-ee3bd9cd-a22d-4c16-85ed-e9d53aaceae8.png)

Think about it.

**Comment by Giorgionocera** [comment]
We need to align the right text "The total liquidity is [...]".

Please, could you do that?

**Comment by Giorgionocera** [comment]
Thank you!
