### ISSUE TITLE
Embolding Pool Titles

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#411]
We need to embold title inside Pool Detail Page. TItile of first two sections are now regular instead of medium. 
<img width="300" alt="Schermata 2022-07-29 alle 00 16 40" src="https://user-images.githubusercontent.com/92384659/181647011-1226c07f-ead7-4fb5-b3e6-7a1601f190b4.png">

<img width="451" alt="Schermata 2022-07-29 alle 00 16 38" src="https://user-images.githubusercontent.com/92384659/181647018-e47b0653-d033-4948-a765-1508172f035d.png">

**Comment by Giorgionocera** [comment]
Thank you!
