### ISSUE TITLE
Copy Fix

### ISSUE THREAD

**Issue by giannnni** [bitsongofficial/sinfonia-ui#412]
I think we could differentiate this little informational text by explaining the duration of bonding period and the different amount of rewards.
<img width="1314" alt="Schermata 2022-07-29 alle 00 22 08" src="https://user-images.githubusercontent.com/92384659/181647537-b28c0ba5-2a85-47b3-8b65-17bc41107cb2.png">

My suggestion is:
Bond Assets for 1 day to earn low rewards and swap fees.
Bond Assets for 7 day to earn medium rewards and swap fees.
Bond Assets for 14 day to earn high rewards and swap fees.

What do you think about it?

**Comment by DavideSegullo** [comment]
I like it, it's a better hint for the users

**Comment by Giorgionocera** [comment]
I think it could be ok, but let's use 7 days and 14 days.

**Comment by giulioaiello** [comment]
i agree with you guys

**Comment by Giorgionocera** [comment]
Let's move it @DavideSegullo ! 😄

**Comment by DavideSegullo** [comment]
@DavideSegullo I did it

**Comment by Giorgionocera** [comment]
Thank you!
