### ISSUE TITLE
Fan token tab change

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#71]
On the Fan token page, the effect of changing from one tab to another must be a fading effect. At the moment, we use a swapping effect.

**Comment by Giorgionocera** [comment]
It is not the best solution. We need to fix it.

**Comment by EnricoBarbieri1997** [comment]
Glitches arises from the social pool as the button really stands out. We could remove transition animation entirerly.

**Comment by Giorgionocera** [comment]
It is ok at the moment. Thank you!
