### ISSUE TITLE
Logo change light mode

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#85]
On switching from light to dark mode or vice versa, it will happen that the logo is not updated correctly. On a second change, it will change to the correct version.

Example step by step.

1) Open Sinfonia (correct logo):
<img width="1680" alt="Schermata 2022-04-01 alle 10 25 26" src="https://user-images.githubusercontent.com/13519292/161226327-49e261ad-1452-4ef4-9dbc-ad47cd0832ab.png">

2) Switch light mode: -> wrong logo
<img width="1680" alt="Schermata 2022-04-01 alle 10 25 52" src="https://user-images.githubusercontent.com/13519292/161226602-2f2dd095-abd5-4c3a-9ce2-836336c5cdac.png">

3) Move to a new page (e.g., swap):
<img width="1680" alt="Schermata 2022-04-01 alle 10 26 30" src="https://user-images.githubusercontent.com/13519292/161226767-d7675f5a-8a81-4cda-81a4-b4c64f3d84ab.png">

4) Switch dark mode: -> wrong logo
<img width="1680" alt="Schermata 2022-04-01 alle 10 26 37" src="https://user-images.githubusercontent.com/13519292/161226858-275054c4-f2a3-4797-891e-0460248fe33f.png">
ong logo

Moreover, **the light/dark mode is forgotten on refresh**.

**Comment by Giorgionocera** [comment]
Thank you @EnricoBarbieri1997 . @giannnni, we need to change the light mode logo.
<img width="234" alt="Schermata 2022-04-06 alle 16 16 46" src="https://user-images.githubusercontent.com/13519292/161995741-aedc3a8d-24a0-499b-b54e-4897cc938b0a.png">

**Comment by giannnni** [comment]
<UPDATED> Light Mode Sinfonia logo version.

<img width="622" alt="Schermata 2022-04-07 alle 14 17 51" src="https://user-images.githubusercontent.com/92384659/162196849-c08b200d-9b15-4fab-a152-e25ba19a6ef0.png">

**Comment by Giorgionocera** [comment]
Thank you @giannnni! @EnricoBarbieri1997 we can move forward for the implementation

**Comment by Giorgionocera** [comment]
Thank you!
