### ISSUE TITLE
Light mode on Analytics tab in Fan token

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#86]
When light mode is enabled, on the Fan token page, on the analytics tab, many issues with shadows occur.

Implementation:
![lightmode-analytics-issue](https://user-images.githubusercontent.com/13519292/161230439-75d22f50-a790-4d75-b307-fab7f8fd2674.jpg)

**Comment by EnricoBarbieri1997** [comment]
Fixed in previous commits

**Comment by Giorgionocera** [comment]
Thank you!
