### ISSUE TITLE
Light/Dark mode switching

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#87]
Switching from dark mode to light mode and vice versa, some colors are wrong.

Implementation:

Switching to dark mode:
![dark-mode-issue](https://user-images.githubusercontent.com/13519292/161231591-a932dc23-3822-4569-bbe6-61e376f05a5b.jpg)

Switching to light mode:
![light-mode-issue](https://user-images.githubusercontent.com/13519292/161231649-f025bcca-745b-4c78-af2d-74891dfbf223.jpg)

Maybe it is linked to issue #85 (give it a look).

**Comment by DavideSegullo** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/17269969/161238381-6a89494a-004d-4a5b-8926-b45c47182ae7.png">

**Comment by Giorgionocera** [comment]
Thank you!
