### ISSUE TITLE
Empty table text

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#88]
The empty transactions history table should have text.

Implementation:
![transaction-history](https://user-images.githubusercontent.com/13519292/161234354-377c3d7e-3610-4de2-8410-8368c7ba1fdc.jpg)

Design:
![empty-table-design](https://user-images.githubusercontent.com/13519292/161234382-8c07e8f7-625f-4b2a-9bd9-eafd98539266.jpg)

**Comment by EnricoBarbieri1997** [comment]
fixed in 2139780136b8cd328e9b64e410f29c108ba14b17
