### ISSUE TITLE
Add cookie bar

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/sinfonia-ui#93]
Add the cookie bar on Sinfonia to accept or decline the google analytics cookies.

Reference:
![cookie-bar](https://user-images.githubusercontent.com/13519292/161576764-be742ed6-f9c9-4e62-bd22-01e93bca6807.jpg)

**Comment by giannnni** [comment]
Done, ready to review. 
![image](https://user-images.githubusercontent.com/92384659/162424641-1bc31ac7-2bba-48c7-8683-1410e0597250.png)

**Comment by giannnni** [comment]
Done, ready to review.

<img width="995" alt="Schermata 2022-04-08 alle 13 11 12" src="https://user-images.githubusercontent.com/92384659/162424695-4bca504a-6845-4c70-8c07-fba790998e0b.png">

**Comment by Giorgionocera** [comment]
Thank you @giannnni. Let's move to the development @DavideSegullo !

**Comment by Giorgionocera** [comment]
We moved this text inside the initial disclaimer in accord with the legal department. 
Thank you.
